### ISSUE TITLE
Closing ledger after failure on AddEntry may lead to data loss

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#100]
While debugging the flaky test testBookieNotAvailableDuringTransaction I noticed that we are calling LedgerHandle#close in case of error during asyncAddEntry.

The "close" method will "close" ledger metadata and sometimes "chops" the ledger so that some entry which is before the LastAddConfirmed/LastAddPushed

> This is the error which causes the closing of the ledger:
> Apr 04, 2017 9:04:50 AM org.apache.bookkeeper.client.PendingAddOp submitCallback
> SEVERE: Write of ledger entry to quorum failed: L5 E3
> Apr 04, 2017 9:04:50 AM org.apache.bookkeeper.client.PendingAddOp submitCallback
> SEVERE: Write of ledger entry to quorum failed: L5 E4
> Apr 04, 2017 9:04:50 AM herddb.cluster.BookkeeperCommitLog handleBookKeeperAsyncFailure
> Apr 04, 2017 9:04:50 AM herddb.cluster.BookkeeperCommitLog handleBookKeeperAsyncFailure
> SEVERE: bookkeeper async failure on tablespace c378614f1a774a0cb49f3a2901d3c762 while writing entry LogEntry{type=5, tableSpace=default, transactionId=1, tableName=null, key=null, value=null, timestamp=1491289490484}
> org.apache.bookkeeper.client.BKException$BKNotEnoughBookiesException
> 	at org.apache.bookkeeper.client.BKException.create(BKException.java:58)
> 	at herddb.cluster.BookkeeperCommitLog$CommitFileWriter.lambda$writeEntry$66(BookkeeperCommitLog.java:113)
> 	at herddb.cluster.BookkeeperCommitLog$CommitFileWriter$$Lambda$21/375466577.addComplete(Unknown Source)
> 	at org.apache.bookkeeper.client.PendingAddOp.submitCallback(PendingAddOp.java:244)
> 	at org.apache.bookkeeper.client.LedgerHandle.errorOutPendingAdds(LedgerHandle.java:937)
> 	at org.apache.bookkeeper.client.LedgerHandle$2.safeRun(LedgerHandle.java:337)
> 	at org.apache.bookkeeper.util.SafeRunnable.run(SafeRunnable.java:31)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)

On "failed" runs we have:

> Apr 04, 2017 9:04:50 AM herddb.cluster.BookkeeperCommitLog$CommitFileWriter close
> SEVERE: Closing ledger 5, with LastAddConfirmed=0, LastAddPushed=0 length=59
 

On "good" runs we have:
> Apr 04, 2017 9:04:50 AM herddb.cluster.BookkeeperCommitLog$CommitFileWriter close
> SEVERE: Closing ledger 5, with LastAddConfirmed=3, LastAddPushed=3 length=170

The partial fix is not to close the ledger in case of AddEntry failures, I will ask on BookKeeper mailing list for a better solution

**Comment by eolivelli** [comment]
This fix is not good

**Comment by eolivelli** [comment]
It was a stupid bug, we were skipping recovery if the LastAddConfirmed entry was the first one (id = 0)
