### ISSUE TITLE
Handle errors on callback on BookKeeperCommitLog

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#110]
RuntimeExceptions thrown from the callback passed to BookKeeperCommitLog#recovery must fail the recovery

**Comment by eolivelli** [comment]
This is an example

```
17-05-05-09-17-20       herddb.cluster.BookkeeperCommitLog May 05, 2017 9:17:20 AM herddb.cluster.BookkeeperCommitLog$1 readComplete
SEVERE: error while processing data: java.lang.RuntimeException: herddb.storage.DataStorageManagerException: invalid transaction id 987, only []
java.lang.RuntimeException: herddb.storage.DataStorageManagerException: invalid transaction id 987, only []
        at herddb.core.TableSpaceManager$ApplyEntryOnRecovery.accept(TableSpaceManager.java:1418)
        at herddb.core.TableSpaceManager$ApplyEntryOnRecovery.accept(TableSpaceManager.java:1408)
        at herddb.cluster.BookkeeperCommitLog$1.readComplete(BookkeeperCommitLog.java:350)
        at org.apache.bookkeeper.client.PendingReadOp.submitCallback(PendingReadOp.java:399)
        at org.apache.bookkeeper.client.PendingReadOp.readEntryComplete(PendingReadOp.java:369)
        at org.apache.bookkeeper.proto.PerChannelBookieClient$ReadCompletion$1.readEntryComplete(PerChannelBookieClient.java:930)
        at org.apache.bookkeeper.proto.PerChannelBookieClient.handleReadResponse(PerChannelBookieClient.java:868)
        at org.apache.bookkeeper.proto.PerChannelBookieClient$7.safeRun(PerChannelBookieClient.java:793)
        at org.apache.bookkeeper.util.SafeRunnable.run(SafeRunnable.java:31)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: herddb.storage.DataStorageManagerException: invalid transaction id 987, only []
        at herddb.core.TableSpaceManager.apply(TableSpaceManager.java:293)
        at herddb.core.TableSpaceManager$ApplyEntryOnRecovery.accept(TableSpaceManager.java:1416)
        ... 13 more

```
