### ISSUE TITLE
Very slow recovery with commit of batch of deletes with a BRIN index

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#127]
This is the sample of the stacktrace of the booting thread
```
"hdb-cavallo-activator" #17 daemon prio=5 os_prio=0 tid=0x00007fef7950c000 nid=0xf1b6 runnable [0x00007fef5da40000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.fs.UnixNativeDispatcher.open0(Native Method)
        at sun.nio.fs.UnixNativeDispatcher.open(UnixNativeDispatcher.java:71)
        at sun.nio.fs.UnixChannelFactory.open(UnixChannelFactory.java:257)
        at sun.nio.fs.UnixChannelFactory.newFileChannel(UnixChannelFactory.java:136)
        at sun.nio.fs.UnixChannelFactory.newFileChannel(UnixChannelFactory.java:148)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:212)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at herddb.file.FileDataStorageManager.readIndexPage(FileDataStorageManager.java:209)
        at herddb.index.brin.BRINIndexManager$IndexDataStorageImpl.loadDataPage(BRINIndexManager.java:325)
        at herddb.index.brin.BlockRangeIndex$Block.ensureBlockLoaded(BlockRangeIndex.java:329)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:295)
        at herddb.index.brin.BlockRangeIndex.lambda$delete$0(BlockRangeIndex.java:605)
        at herddb.index.brin.BlockRangeIndex$$Lambda$102/88879132.accept(Unknown Source)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at herddb.index.brin.BlockRangeIndex.delete(BlockRangeIndex.java:605)
        at herddb.index.brin.BRINIndexManager.recordDeleted(BRINIndexManager.java:294)
        at herddb.core.TableManager.applyDelete(TableManager.java:1137)
        at herddb.core.TableManager.onTransactionCommit(TableManager.java:969)
        at herddb.core.TableSpaceManager.apply(TableSpaceManager.java:325)
        at herddb.core.TableSpaceManager$ApplyEntryOnRecovery.accept(TableSpaceManager.java:1429)
        at herddb.core.TableSpaceManager$ApplyEntryOnRecovery.accept(TableSpaceManager.java:1421)
        at herddb.file.FileCommitLog.recovery(FileCommitLog.java:398)
        at herddb.core.TableSpaceManager.recover(TableSpaceManager.java:259)
        at herddb.core.TableSpaceManager.start(TableSpaceManager.java:195)
        at herddb.core.DBManager.handleTableSpace(DBManager.java:484)
        at herddb.core.DBManager.manageTableSpaces(DBManager.java:1060)
        at herddb.core.DBManager.executeActivator(DBManager.java:1020)
        at herddb.core.DBManager.access$500(DBManager.java:107)
        at herddb.core.DBManager$Activator.run(DBManager.java:971)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by diegosalvi** [comment]
There are 2 problems in
```
at herddb.index.brin.BlockRangeIndex$Block.ensureBlockLoaded(BlockRangeIndex.java:329)
at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:295)
at herddb.index.brin.BlockRangeIndex.lambda$delete$0(BlockRangeIndex.java:605)
at herddb.index.brin.BlockRangeIndex$$Lambda$102/88879132.accept(Unknown Source)
at java.lang.Iterable.forEach(Iterable.java:75)
at herddb.index.brin.BlockRangeIndex.delete(BlockRangeIndex.java:605)
```

`at herddb.index.brin.BlockRangeIndex.delete(BlockRangeIndex.java:605)` iterates the deletion on **every** node, it should stop on deletion done!

`at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:295)` invokes ensureBlockLoaded every time, without checking if the key is in range

In the current error case the index really have just 3 keys with a huge number of values mapped to them, even checking the block key limits before load won't suffice, too many pages will be loaded for every deletion

**Comment by diegosalvi** [comment]
Added improvements to:

- avoid to check a node multiple times
- avoid to load node data for a node if given key doesn't match node limits

**Comment by diegosalvi** [comment]
Next improvement would be execute batched deletes on transaction commit to limit brin nodes looping
