### ISSUE TITLE
Boot error due to missing table checkpoint file

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#129]
SEVERE: Booting tablespace q1 on maiale, uuid 3d342484554a4bffb8ab7bf252e6ee04

17-07-17-09-39-41       herddb.file.FileCommitLog Jul 17, 2017 9:39:41 AM herddb.file.FileCommitLog recovery
SEVERE: recovery, snapshotSequenceNumber: (3,82279)

17-07-17-09-39-40       herddb.core.TableManager Jul 17, 2017 9:39:40 AM herddb.core.TableManager start
SEVERE: loading table q1_header, uuid a916b6b8-a659-4488-a210-4cd3ffd88a9f

17-07-17-09-39-40       herddb.core.TableManager Jul 17, 2017 9:39:40 AM herddb.core.TableManager start
SEVERE: recovery table at (3,72956)

17-07-17-09-39-40       herddb.core.TableManager Jul 17, 2017 9:39:40 AM herddb.core.TableManager start
SEVERE: loaded 11,012 keys for table q1_header, newPageId 452, nextPrimaryKeyValue 1, activePages {384=[1048440,214,0], 449=[269702,214,0], 93=[1048515,214,1710]}

logs/herddb.file.FileCommitLog-17-07-17.log:FINE: SKIP ENTRY (3,82215), LogEntry{type=2, tableSpace=q1, transactionId=18583, tableName=q1_header, key=080000000000000eaa0400000001, value=02000446726f6d0300264361726c61204d616363696f6e69203c71616f706261746368406469656e6e65612e636f6d3e, timestamp=1498729833251}
logs/herddb.file.FileCommitLog-17-07-17.log:FINE: RECOVER ENTRY (3,163033), LogEntry{type=4, tableSpace=q1, transactionId=35421, tableName=q1_header, key=080000000000000eaa0400000001, value=null, timestamp=1499334689464}

SEVERE: cannot handle tablespace q1
herddb.log.LogNotAvailableException: java.lang.IllegalStateException: corrupted transaction log: key 080000000000000eaa0400000001 is not present in table q1_header
        at herddb.file.FileCommitLog.recovery(FileCommitLog.java:412)
        at herddb.core.TableSpaceManager.recover(TableSpaceManager.java:259)
        at herddb.core.TableSpaceManager.start(TableSpaceManager.java:195)
        at herddb.core.DBManager.handleTableSpace(DBManager.java:484)
        at herddb.core.DBManager.manageTableSpaces(DBManager.java:1060)
        at herddb.core.DBManager.executeActivator(DBManager.java:1020)
        at herddb.core.DBManager.access$500(DBManager.java:107)
        at herddb.core.DBManager$Activator.run(DBManager.java:971)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: corrupted transaction log: key 080000000000000eaa0400000001 is not present in table q1_header
        at herddb.core.TableManager.applyDelete(TableManager.java:1079)
        at herddb.core.TableManager.onTransactionCommit(TableManager.java:969)
        at herddb.core.TableSpaceManager.apply(TableSpaceManager.java:325)
        at herddb.core.TableSpaceManager$ApplyEntryOnRecovery.accept(TableSpaceManager.java:1429)
        at herddb.core.TableSpaceManager$ApplyEntryOnRecovery.accept(TableSpaceManager.java:1421)
        at herddb.file.FileCommitLog.recovery(FileCommitLog.java:398)
        ... 8 more

**Comment by eolivelli** [comment]
On disk for each table we have 2 .checkpoint files, one for 82279 checkpoint and one for 72956 checkpoint) but  in one table there is only the file for the "old" 72956 checkpoint.

points:
- only one file should be kept per table
- why the lost file is the one which should not be deleted ?

there is no trace of logs, so it is impossible to see how the checkpoint procedure worked.

Another odd thing is that at the same time the same problem appeared in another staging machine (not in the same cluster). Machines share the same VMWare system
