### ISSUE TITLE
BRIN next block isn't properly updated

### ISSUE THREAD

**Issue by diegosalvi** [diennea/herddb#136]
Each block can point to a next block when it split. Such `next` field is modified only during split operations and it isn't kept in account during block deletions (during a checkpoint when a block size reach 0).

After a block deletion his sibling still point to it generating 

```
herddb.model.StatementExecutionException: java.lang.RuntimeException: java.io.IOException: herddb.storage.DataStorageManagerException: java.nio.file.NoSuchFileException: /data/es/./dbdata/data/657b1aa061e849cda3d335582da7ad19.tablespace/33ea9860-dc3b-433f-9d4d-de620fe84885.index/52149.page
        at herddb.core.TableSpaceManager.commitTransaction(TableSpaceManager.java:1411)
        at herddb.core.TableSpaceManager.executeStatement(TableSpaceManager.java:1019)
        at herddb.core.DBManager.executeStatement(DBManager.java:577)
        at herddb.core.DBManager.executePlan(DBManager.java:644)
        at herddb.server.ServerSideConnectionPeer.handleExecuteStatement(ServerSideConnectionPeer.java:560)
        at herddb.server.ServerSideConnectionPeer.messageReceived(ServerSideConnectionPeer.java:126)
        at herddb.network.netty.NettyChannel.lambda$messageReceived$0(NettyChannel.java:82)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by diegosalvi** [comment]
Block deletion was missing at all, they were just "abandoned" at checkpoint time but never unloaded from page cache nor next references were evere updated.
