### ISSUE TITLE
NullPointerException on Recovery

### ISSUE THREAD

**Issue by aluccaroni** [diennea/herddb#152]
Below an error on startup after a forced kill of the service:

17-10-13-12-14-32       herddb.core.DBManager Oct 13, 2017 12:14:32 PM herddb.core.DBManager start
SEVERE: Registering on metadata storage manager my data: NodeMetadata{nodeId=gatto, metadataStorageVersion=null, host=localhost, port=7001, ssl=false}

17-10-13-12-14-32       herddb.core.DBManager Oct 13, 2017 12:14:32 PM herddb.core.DBManager handleTableSpace
SEVERE: Booting tablespace q1 on gatto, uuid 4f4210f4cd5b4e459a70125dbf139496

17-10-13-12-14-33       herddb.core.DBManager Oct 13, 2017 12:14:33 PM herddb.core.DBManager handleTableSpace
SEVERE: Error Booting tablespace q1 on gatto

17-10-13-12-14-33       herddb.core.DBManager Oct 13, 2017 12:14:33 PM herddb.core.DBManager handleTableSpace
SEVERE: Error
herddb.log.LogNotAvailableException: java.lang.NullPointerException
        at herddb.file.FileCommitLog.recovery(FileCommitLog.java:415)
        at herddb.core.TableSpaceManager.recover(TableSpaceManager.java:270)
        at herddb.core.TableSpaceManager.start(TableSpaceManager.java:206)
        at herddb.core.DBManager.handleTableSpace(DBManager.java:488)
        at herddb.core.DBManager.manageTableSpaces(DBManager.java:1123)
        at herddb.core.DBManager.executeActivator(DBManager.java:1083)
        at herddb.core.DBManager.access$500(DBManager.java:110)
        at herddb.core.DBManager$Activator.run(DBManager.java:1031)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at herddb.core.TableSpaceManager.apply(TableSpaceManager.java:488)
        at herddb.core.TableSpaceManager$ApplyEntryOnRecovery.accept(TableSpaceManager.java:1444)
        at herddb.core.TableSpaceManager$ApplyEntryOnRecovery.accept(TableSpaceManager.java:1436)
        at herddb.file.FileCommitLog.recovery(FileCommitLog.java:401)
        ... 8 more

**Comment by diegosalvi** [comment]
This behaviour is caused by empty metadata files.

Metadata files MUST be flushed and synched. They cannot be presumed written if not synched correctly
