### ISSUE TITLE
Error while calling JDBC Connection#close() twice

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#168]
If you call Connection#close() twice you get this error
```
java.lang.IllegalStateException: Object has already been returned to this pool or is invalid
	at org.apache.commons.pool2.impl.GenericObjectPool.returnObject(GenericObjectPool.java:551)
	at herddb.jdbc.BasicHerdDBDataSource.releaseConnection(BasicHerdDBDataSource.java:145)
	at herddb.jdbc.HerdDBConnection.close(HerdDBConnection.java:181)
```

**Comment by eolivelli** [comment]
This issue was reported by @victorlbb
Fix merged to current master
