### ISSUE TITLE
Restarting server can take a lot of time in case of many changes on same rows for an indexed column

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#190]
This is the stacktrace, the BRINManager needs to read from disk the same pages a lot of times in a very memory-constrained JVM.

   java.lang.Thread.State: RUNNABLE
        at net.jpountz.xxhash.XXHashJNI.XXH64_update(Native Method)
        at net.jpountz.xxhash.StreamingXXHash64JNI.update(StreamingXXHash64JNI.java:60)
        at herddb.utils.XXHash64Utils$HashingStream.read(XXHash64Utils.java:96)
        at java.io.DataInputStream.readByte(DataInputStream.java:265)
        at herddb.utils.ExtendedDataInputStream.readVInt(ExtendedDataInputStream.java:47)
        at herddb.utils.ExtendedDataInputStream.readArray(ExtendedDataInputStream.java:183)
        at herddb.index.brin.BRINIndexManager$PageContents.deserialize(BRINIndexManager.java:161)
        at herddb.index.brin.BRINIndexManager$IndexDataStorageImpl.lambda$loadDataPage$0(BRINIndexManager.java:338)
        at herddb.index.brin.BRINIndexManager$IndexDataStorageImpl$$Lambda$115/732817909.read(Unknown Source)
        at herddb.file.FileDataStorageManager.readIndexPage(FileDataStorageManager.java:264)
        at herddb.index.brin.BRINIndexManager$IndexDataStorageImpl.loadDataPage(BRINIndexManager.java:337)
        at herddb.index.brin.BlockRangeIndex$Block.ensureBlockLoaded(BlockRangeIndex.java:340)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:303)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:332)
        at herddb.index.brin.BlockRangeIndex.lambda$delete$0(BlockRangeIndex.java:650)
        at herddb.index.brin.BlockRangeIndex$$Lambda$113/1856989764.accept(Unknown Source)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at herddb.index.brin.BlockRangeIndex.delete(BlockRangeIndex.java:650)
        at herddb.index.brin.BRINIndexManager.recordUpdated(BRINIndexManager.java:327)
        at herddb.core.TableManager.applyUpdate(TableManager.java:1378)
        at herddb.core.TableManager.apply(TableManager.java:1158)
        at herddb.core.TableSpaceManager.apply(TableSpaceManager.java:470)
        at herddb.core.TableSpaceManager$ApplyEntryOnRecovery.accept(TableSpaceManager.java:1464)
        at herddb.core.TableSpaceManager$ApplyEntryOnRecovery.accept(TableSpaceManager.java:1456)
        at herddb.file.FileCommitLog.recovery(FileCommitLog.java:408)
        at herddb.core.TableSpaceManager.recover(TableSpaceManager.java:271)
        at herddb.core.TableSpaceManager.start(TableSpaceManager.java:208)
        at herddb.core.DBManager.handleTableSpace(DBManager.java:503)
        at herddb.core.DBManager.manageTableSpaces(DBManager.java:1142)
        at herddb.core.DBManager.executeActivator(DBManager.java:1102)
        at herddb.core.DBManager.access$500(DBManager.java:112)
        at herddb.core.DBManager$Activator.run(DBManager.java:1050)
        at java.lang.Thread.run(Thread.java:748)

**Comment by diegosalvi** [comment]
After last BRIN changes could you please fill another stacktrace with new implementation? Delete code should be faster than before

**Comment by aluccaroni** [comment]
```
"hdb-gallina-activator" #34 daemon prio=5 os_prio=0 cpu=72324,22ms elapsed=72,48s tid=0x00007f81f18e7000 nid=0xb6b3 runnable  [0x00007f70eb5f8000]
   java.lang.Thread.State: RUNNABLE
        at herddb.index.brin.BlockRangeIndex$Block.delete(BlockRangeIndex.java:382)
        at herddb.index.brin.BlockRangeIndex.delete(BlockRangeIndex.java:1051)
        at herddb.index.brin.BRINIndexManager.recordDeleted(BRINIndexManager.java:420)
        at herddb.core.TableManager.applyDelete(TableManager.java:1683)
        at herddb.core.TableManager.onTransactionCommit(TableManager.java:1473)
        at herddb.core.TableSpaceManager.apply(TableSpaceManager.java:363)
        at herddb.core.TableSpaceManager$ApplyEntryOnRecovery.accept(TableSpaceManager.java:1815)
        at herddb.core.TableSpaceManager$ApplyEntryOnRecovery.accept(TableSpaceManager.java:1807)
        at herddb.file.FileCommitLog.recovery(FileCommitLog.java:670)
        at herddb.core.TableSpaceManager.recover(TableSpaceManager.java:295)
        at herddb.core.TableSpaceManager.start(TableSpaceManager.java:232)
        at herddb.core.DBManager.handleTableSpace(DBManager.java:535)
        at herddb.core.DBManager.manageTableSpaces(DBManager.java:1107)
        at herddb.core.DBManager.executeActivator(DBManager.java:1057)
        at herddb.core.DBManager.access$500(DBManager.java:115)
        at herddb.core.DBManager$Activator.run(DBManager.java:1005)
        at java.lang.Thread.run(java.base@11.0.4/Thread.java:834)
```

**Comment by aluccaroni** [comment]
@diegosalvi can we close this issue?

**Comment by diegosalvi** [comment]
It can be closed
