### ISSUE TITLE
Failed to restart long running herddb with bookkeeper

### ISSUE THREAD

**Issue by diegosalvi** [diennea/herddb#194]
`herddb.log.LogNotAvailableException: org.apache.bookkeeper.client.BKException$BKReadException: Error while reading ledger
        at herddb.cluster.BookkeeperCommitLog.recovery(BookkeeperCommitLog.java:356)
        at herddb.core.TableSpaceManager.recover(TableSpaceManager.java:271)
        at herddb.core.TableSpaceManager.start(TableSpaceManager.java:208)
        at herddb.core.DBManager.handleTableSpace(DBManager.java:503)
        at herddb.core.DBManager.manageTableSpaces(DBManager.java:1142)
        at herddb.core.DBManager.executeActivator(DBManager.java:1102)
        at herddb.core.DBManager.access$500(DBManager.java:112)
        at herddb.core.DBManager$Activator.run(DBManager.java:1050)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: org.apache.bookkeeper.client.BKException$BKReadException: Error while reading ledger
        at org.apache.bookkeeper.client.SyncCallbackUtils.finish(SyncCallbackUtils.java:69)
        at org.apache.bookkeeper.client.SyncCallbackUtils$SyncReadCallback.readComplete(SyncCallbackUtils.java:217)
        at org.apache.bookkeeper.client.LedgerHandle$6.onFailure(LedgerHandle.java:796)
        at org.apache.bookkeeper.common.concurrent.FutureEventListener.accept(FutureEventListener.java:38)
        at org.apache.bookkeeper.common.concurrent.FutureEventListener.accept(FutureEventListener.java:26)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        ... 1 more
`

`18-05-23-09-21-24       Ledger fence request received for ledger: 15 from address: local:E:53b182fe
18-05-23-09-21-25       IOException while reading entry: 1 from ledger 2
18-05-23-09-21-25       java.io.FileNotFoundException: No file for log 0 for 2 with location 45980
java.io.FileNotFoundException: No file for log 0 for 2 with location 45980
        at org.apache.bookkeeper.bookie.EntryLogger.findFile(EntryLogger.java:1165)
        at org.apache.bookkeeper.bookie.EntryLogger.getChannelForLogId(EntryLogger.java:1100)
        at org.apache.bookkeeper.bookie.EntryLogger.internalReadEntry(EntryLogger.java:1002)
        at org.apache.bookkeeper.bookie.EntryLogger.readEntry(EntryLogger.java:1051)
        at org.apache.bookkeeper.bookie.InterleavedLedgerStorage.getEntry(InterleavedLedgerStorage.java:300)
        at org.apache.bookkeeper.bookie.SortedLedgerStorage.getEntry(SortedLedgerStorage.java:153)
        at org.apache.bookkeeper.bookie.LedgerDescriptorImpl.readEntry(LedgerDescriptorImpl.java:153)
        at org.apache.bookkeeper.bookie.Bookie.readEntry(Bookie.java:1283)
        at org.apache.bookkeeper.proto.ReadEntryProcessorV3.readEntry(ReadEntryProcessorV3.java:175)
        at org.apache.bookkeeper.proto.ReadEntryProcessorV3.readEntry(ReadEntryProcessorV3.java:155)
        at org.apache.bookkeeper.proto.ReadEntryProcessorV3.getReadResponse(ReadEntryProcessorV3.java:218)
        at org.apache.bookkeeper.proto.ReadEntryProcessorV3.executeOp(ReadEntryProcessorV3.java:261)
        at org.apache.bookkeeper.proto.ReadEntryProcessorV3.safeRun(ReadEntryProcessorV3.java:257)
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.base/java.lang.Thread.run(Thread.java:844)
`

**Comment by eolivelli** [comment]
@diegosalvi this can be a fix for your case #196

**Comment by eolivelli** [comment]
Fixed with #196
