### ISSUE TITLE
Execute a query to an unknown tablespace locks the statement 

### ISSUE THREAD

**Issue by nicoloboschi** [diennea/herddb#195]
To reproduce:
Open CLI and execute: SELECT count(*) from bad.systables

**Comment by nicoloboschi** [comment]
After checking logs I have seen that the statement is not locked but is only slow because it waits for determinate times and it is the right behaviour. 
`herddb.model.StatementExecutionException: internal error,Calcite subSchema for bad is null,tableSpaceManager is null,maybe table space bad is not yet started on this node
        at herddb.sql.CalcitePlanner.runPlanner(CalcitePlanner.java:410)
        at herddb.sql.CalcitePlanner.translate(CalcitePlanner.java:276)
        at herddb.server.ServerSideConnectionPeer.handleOpenScanner(ServerSideConnectionPeer.java:394)
        at herddb.server.ServerSideConnectionPeer.messageReceived(ServerSideConnectionPeer.java:210)
        at herddb.network.netty.NettyChannel.lambda$messageReceived$0(NettyChannel.java:82)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`
