### ISSUE TITLE
Errors while downloading dump on follower

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#229]
In a test env we have two 0.6.0-SNAPSHOT instances

when the follower boot we get this error on the leader:
SEVERE: error on dump
```
herddb.storage.DataStorageManagerException: no such table checkpoint: /data/smtp/smtpref2/dbdata/data/cfd153be90b448e08264febe166e941f.tablespace/buckets.table/33.1.checkpoint
	at herddb.file.FileDataStorageManager.getTableStatus(FileDataStorageManager.java:345)
	at herddb.storage.DataStorageManager.unPinTableCheckpoint(DataStorageManager.java:263)
	at herddb.core.TableSpaceManager.dumpTableSpace(TableSpaceManager.java:850)
	at herddb.core.DBManager.dumpTableSpace(DBManager.java:944)
	at herddb.server.ServerSideConnectionPeer.handleRequestTablespaceDump(ServerSideConnectionPeer.java:493)
	at herddb.server.ServerSideConnectionPeer.messageReceived(ServerSideConnectionPeer.java:155)
	at herddb.network.netty.NettyChannel.lambda$messageReceived$0(NettyChannel.java:81)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)

```
and this error on the follower, which is not able to recover:

```
SEVERE: NettyChannel{name=sviluppo-ref.sviluppo.dna:7001, id=1, socket=[id: 0xb5c0b0a7, L:/10.168.11.26:56624 - R:sviluppo-ref.sviluppo.dna/10.168.10.81:7001] pending 0 msgs}: error java.lang.NullPointerException
java.lang.NullPointerException
        at herddb.core.ReplicaFullTableDataDumpReceiver.receiveTableDataChunk(ReplicaFullTableDataDumpReceiver.java:95)
        at herddb.client.RoutedClientSideConnection.messageReceived(RoutedClientSideConnection.java:196)
        at herddb.network.netty.NettyChannel.lambda$messageReceived$0(NettyChannel.java:81)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)


```

**Comment by eolivelli** [comment]
resolved with 6176ba5
