### ISSUE TITLE
Error during Checkpoint - BLink checkpoint  cannot write negative vLong (got: -19290)

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#236]
java.lang.IllegalArgumentException: cannot write negative vLong (got: -19290)
        at herddb.utils.ExtendedDataOutputStream.writeVLong(ExtendedDataOutputStream.java:55)
        at herddb.index.blink.BLinkKeyToPageIndex$MetadataSerializer.write(BLinkKeyToPageIndex.java:400)
        at herddb.index.blink.BLinkKeyToPageIndex.checkpoint(BLinkKeyToPageIndex.java:281)
        at herddb.core.TableManager.checkpoint(TableManager.java:2110)
        at herddb.core.TableManager.fullCheckpoint(TableManager.java:1818)
        at herddb.core.TableSpaceManager.checkpoint(TableSpaceManager.java:1363)
        at herddb.core.TableSpaceManager.dumpTableSpace(TableSpaceManager.java:780)
        at herddb.core.DBManager.dumpTableSpace(DBManager.java:944)
        at herddb.server.ServerSideConnectionPeer.handleRequestTablespaceDump(ServerSideConnectionPeer.java:493)
        at herddb.server.ServerSideConnectionPeer.messageReceived(ServerSideConnectionPeer.java:155)
        at herddb.network.netty.NettyChannel.lambda$messageReceived$0(NettyChannel.java:81)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by diegosalvi** [comment]
Problem related to node byte size evaluation. A previous commit (f827697d802e52ae0e4c416f914f22fb4b3a458d) increased evaluated size (to 42) for each node elements but such size was also stored in already disk pages with a smaller constant (24).

While deleting entries size evaluation began to drift toward a negative value: entry evaluated size at insertion x + 24, entry evaluated size at removal x + 42.

To fix this issue we can:
a) rollback size evaluation change
b) increase page version number and add compatibility checks to recalculate page size for older versions.

Solution b could support wrong reported size on page file too (pages written with data with both 42 and 24 costants)
