### ISSUE TITLE
Corrupted transaction log after TABLE DROP

### ISSUE THREAD

**Issue by aluccaroni** [diennea/herddb#240]
I've got an error after I perform the DROP of a table and restart the herddb instance. I was performing some bench, so I was continuosly dropping and re-creating the same table.

It seems to be related to the fact that the table existed before and some works was done on it.

```
SEVERE: Error Booting tablespace herd on papera
Aug 06, 2018 2:38:11 PM herddb.core.DBManager handleTableSpace
SEVERE: Error
herddb.log.LogNotAvailableException: java.lang.IllegalStateException: corrupted transaction log: key 7573657234313537303130303730313734383235333539 is not present in table usertable
        at herddb.file.FileCommitLog.recovery(FileCommitLog.java:447)
        at herddb.core.TableSpaceManager.recover(TableSpaceManager.java:276)
        at herddb.core.TableSpaceManager.start(TableSpaceManager.java:213)
        at herddb.core.DBManager.handleTableSpace(DBManager.java:503)
        at herddb.core.DBManager.manageTableSpaces(DBManager.java:1147)
        at herddb.core.DBManager.executeActivator(DBManager.java:1102)
        at herddb.core.DBManager.access$500(DBManager.java:112)
        at herddb.core.DBManager$Activator.run(DBManager.java:1050)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: corrupted transaction log: key 7573657234313537303130303730313734383235333539 is not present in table usertable
        at herddb.core.TableManager.applyUpdate(TableManager.java:1293)
        at herddb.core.TableManager.apply(TableManager.java:1181)
        at herddb.core.TableSpaceManager.apply(TableSpaceManager.java:479)
        at herddb.core.TableSpaceManager$ApplyEntryOnRecovery.accept(TableSpaceManager.java:1491)
        at herddb.core.TableSpaceManager$ApplyEntryOnRecovery.accept(TableSpaceManager.java:1483)
        at herddb.file.FileCommitLog.recovery(FileCommitLog.java:433)
        ... 8 more

Aug 06, 2018 2:38:11 PM herddb.core.DBManager manageTableSpaces
SEVERE: cannot handle tablespace herd
herddb.log.LogNotAvailableException: java.lang.IllegalStateException: corrupted transaction log: key 7573657234313537303130303730313734383235333539 is not present in table usertable
        at herddb.file.FileCommitLog.recovery(FileCommitLog.java:447)
        at herddb.core.TableSpaceManager.recover(TableSpaceManager.java:276)
        at herddb.core.TableSpaceManager.start(TableSpaceManager.java:213)
        at herddb.core.DBManager.handleTableSpace(DBManager.java:503)
        at herddb.core.DBManager.manageTableSpaces(DBManager.java:1147)
        at herddb.core.DBManager.executeActivator(DBManager.java:1102)
        at herddb.core.DBManager.access$500(DBManager.java:112)
        at herddb.core.DBManager$Activator.run(DBManager.java:1050)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: corrupted transaction log: key 7573657234313537303130303730313734383235333539 is not present in table usertable
        at herddb.core.TableManager.applyUpdate(TableManager.java:1293)
        at herddb.core.TableManager.apply(TableManager.java:1181)
        at herddb.core.TableSpaceManager.apply(TableSpaceManager.java:479)
        at herddb.core.TableSpaceManager$ApplyEntryOnRecovery.accept(TableSpaceManager.java:1491)
        at herddb.core.TableSpaceManager$ApplyEntryOnRecovery.accept(TableSpaceManager.java:1483)
        at herddb.file.FileCommitLog.recovery(FileCommitLog.java:433)
        ... 8 more

herddb.log.LogNotAvailableException: java.lang.IllegalStateException: corrupted transaction log: key 7573
herddb.log.LogNotAvailableException: java.lang.IllegalStateException: corrupted transaction log: key 7573657234313537303130303730313734383235333539 is not present in table usertable
        at herddb.file.FileCommitLog.recovery(FileCommitLog.java:447)
        at herddb.core.TableSpaceManager.recover(TableSpaceManager.java:276)
        at herddb.core.TableSpaceManager.start(TableSpaceManager.java:213)
        at herddb.core.DBManager.handleTableSpace(DBManager.java:503)
        at herddb.core.DBManager.manageTableSpaces(DBManager.java:1147)
        at herddb.core.DBManager.executeActivator(DBManager.java:1102)
        at herddb.core.DBManager.access$500(DBManager.java:112)
        at herddb.core.DBManager$Activator.run(DBManager.java:1050)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: corrupted transaction log: key 7573657234313537303130303730313734383235333539 is not present in table usertable
        at herddb.core.TableManager.applyUpdate(TableManager.java:1293)
        at herddb.core.TableManager.apply(TableManager.java:1181)
        at herddb.core.TableSpaceManager.apply(TableSpaceManager.java:479)
        at herddb.core.TableSpaceManager$ApplyEntryOnRecovery.accept(TableSpaceManager.java:1491)
        at herddb.core.TableSpaceManager$ApplyEntryOnRecovery.accept(TableSpaceManager.java:1483)
        at herddb.file.FileCommitLog.recovery(FileCommitLog.java:433)
        ... 8 more
HERDDB will force the Halt of the JVM
```

**Comment by eolivelli** [comment]
In order to fix this we have to change the format of the transaction log, we are now using the "tablename" in order to refer to tables, we have to use the table UUID.

We must preserve compatibility with older versions in order to support upgrades.

It would be great to use only some integer IT instead of the full UUID, we can achive this with some internal lookup table valid inside the single TXLOG file or BookKeeper ledger.

Or we could simply assign an incremental integer ID to every table insteand of a 128 UUID (old database will have the 128bit ID)
