### ISSUE TITLE
Error importing table from MySQL

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#244]
CREATE TABLE `ao_21d670_whitelist_rules` (
  `ALLOWINBOUND` tinyint(1) DEFAULT NULL,
  `EXPRESSION` longtext COLLATE utf8_bin NOT NULL,
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TYPE` varchar(255) COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`ID`)
) 

this is the error.
error:java.sql.SQLException: herddb.model.StatementExecutionException: java.lang.IllegalArgumentException: Unexpected error on cast of value http://www.atlassian.com/* (class herddb.utils.RawString): java.lang.ClassCastException: herddb.utils.RawString cannot be cast to java.lang.Number  query was 'INSERT INTO `ao_21d670_whitelist_rules` VALUES (?,?,?,?)', with values [[0, http://www.atlassian.com/*, 3, WILDCARD_EXPRESSION], [0, 3d194026-dc63-385b-86a6-0cc89001d9a1, 4, APPLICATION_LINK], [0, null://null/*, 5, WILDCARD_EXPRESSION], [0, 33ba34ad-a52f-3e7f-8db1-14d253719ac1, 6, APPLICATION_LINK], [0, 3d194026-dc63-385b-86a6-0cc89001d9a1, 7, APPLICATION_LINK], [0, 33ba34ad-a52f-3e7f-8db1-14d253719ac1, 8, APPLICATION_LINK], [0, http://www.atlassian.com/*, 9, WILDCARD_EXPRESSION], [0, f6ce63b0-7606-3171-9b42-d087e3791629, 10, APPLICATION_LINK]]

**Comment by eolivelli** [comment]
Stacktrace:
SEVERE: NettyChannel{name=unnamed, id=1, socket=[id: 0x9eff6bd3, L:/127.0.0.1:7000 - R:/127.0.0.1:59214] pending 0 msgs}: error java.lang.RuntimeException: Unexpected error on cast of value http://www.atlassian.com/* (class herddb.utils.RawString): java.lang.ClassCastException: herddb.utils.RawString cannot be cast to java.lang.Number
java.lang.RuntimeException: Unexpected error on cast of value http://www.atlassian.com/* (class herddb.utils.RawString): java.lang.ClassCastException: herddb.utils.RawString cannot be cast to java.lang.Number
        at herddb.sql.SQLRecordPredicate.cast(SQLRecordPredicate.java:162)
        at herddb.sql.expressions.TypedJdbcParameterExpression.evaluate(TypedJdbcParameterExpression.java:38)
        at herddb.sql.SQLRecordFunction.computeNewValue(SQLRecordFunction.java:73)
        at herddb.core.TableManager.executeInsert(TableManager.java:850)
        at herddb.core.TableManager.executeStatement(TableManager.java:503)
        at herddb.core.TableSpaceManager.executeTableAwareStatement(TableSpaceManager.java:1069)
        at herddb.core.TableSpaceManager.executeStatement(TableSpaceManager.java:1004)
        at herddb.model.planner.SimpleInsertOp.execute(SimpleInsertOp.java:50)
        at herddb.core.TableSpaceManager.executePlannedOperationStatement(TableSpaceManager.java:1049)
        at herddb.core.TableSpaceManager.executeStatement(TableSpaceManager.java:1007)
        at herddb.core.DBManager.executeStatement(DBManager.java:594)
        at herddb.core.DBManager.executePlan(DBManager.java:665)
        at herddb.server.ServerSideConnectionPeer.handleExecuteStatements(ServerSideConnectionPeer.java:531)
        at herddb.server.ServerSideConnectionPeer.messageReceived(ServerSideConnectionPeer.java:148)
        at herddb.network.netty.NettyChannel.lambda$messageReceived$0(NettyChannel.java:81)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: herddb.utils.RawString cannot be cast to java.lang.Number
        at herddb.sql.SQLRecordPredicate.cast(SQLRecordPredicate.java:153)
        ... 19 more

**Comment by eolivelli** [comment]
Reproducer test case
```
@Test
    public void insertWithoutValuesAndPrimaryKeyIsNotTheFirstColumn() throws Exception {
        String nodeId = "localhost";
        try (DBManager manager = new DBManager("localhost", new MemoryMetadataStorageManager(), new MemoryDataStorageManager(), new MemoryCommitLogManager(), null, null);) {
            manager.start();
            CreateTableSpaceStatement st1 = new CreateTableSpaceStatement("tblspace1", Collections.singleton(nodeId), nodeId, 1, 0, 0);
            manager.executeStatement(st1, StatementEvaluationContext.DEFAULT_EVALUATION_CONTEXT(), TransactionContext.NO_TRANSACTION);
            manager.waitForTablespace("tblspace1", 10000);

            execute(manager, "CREATE TABLE `ao_21d670_whitelist_rules` (\n"
                    + "  `ALLOWINBOUND` tinyint(1) DEFAULT NULL,\n"
                    + "  `EXPRESSION` longtext COLLATE utf8_bin NOT NULL,\n"
                    + "  `ID` int(11) NOT NULL AUTO_INCREMENT,\n"
                    + "  `TYPE` varchar(255) COLLATE utf8_bin NOT NULL,\n"
                    + "  PRIMARY KEY (`ID`)\n"
                    + ") ", Collections.emptyList());

            execute(manager, "INSERT INTO `ao_21d670_whitelist_rules` VALUES (?,?,?,?)\n"
                    + "", Arrays.asList(0, "http://www.atlassian.com/*", 3, "WILDCARD_EXPRESSION"));

        }
    }
```
It has been introduced with the fix for #230  and commit aa1e35f540f56a0ea8058e4a529b8977c80583fc	
"Issue-230 'Select *' does not work on Heap tables using JDBC"
