### ISSUE TITLE
Error while deleting on a multi colum pk

### ISSUE THREAD

**Issue by diegosalvi** [diennea/herddb#276]
When deleting on a table with a multi column pk but using only a prefix I got this:

```herddb.server.ServerSideConnectionPeer Oct 11, 2018 4:23:11 PM herddb.server.ServerSideConnectionPeer handleExecuteStatement
SEVERE: unexpected error on query DELETE FROM q1.q1_ADDITIONAL_INFO WHERE MSG_ID = ?, parameters: [578687]:java.lang.IllegalArgumentException: fromKey > toKey
java.lang.IllegalArgumentException: fromKey > toKey
        at java.base/java.util.TreeMap$NavigableSubMap.<init>(TreeMap.java:1365)
        at java.base/java.util.TreeMap$AscendingSubMap.<init>(TreeMap.java:1852)
        at java.base/java.util.TreeMap.subMap(TreeMap.java:910)
        at herddb.index.blink.BLink$Node.copyRange(BLink.java:1967)
        at herddb.index.blink.BLink$ScanIterator.<init>(BLink.java:2930)
        at herddb.index.blink.BLink.scan(BLink.java:506)
        at herddb.index.blink.BLinkKeyToPageIndex.scanner(BLinkKeyToPageIndex.java:171)
        at herddb.core.TableManager.accessTableData(TableManager.java:2506)
        at herddb.core.TableManager.executeDelete(TableManager.java:986)
        at herddb.core.TableManager.executeStatement(TableManager.java:511)
        at herddb.core.TableSpaceManager.executeTableAwareStatement(TableSpaceManager.java:1082)
        at herddb.core.TableSpaceManager.executeStatement(TableSpaceManager.java:1017)
        at herddb.model.planner.SimpleDeleteOp.execute(SimpleDeleteOp.java:53)
        at herddb.core.TableSpaceManager.executePlannedOperationStatement(TableSpaceManager.java:1062)
        at herddb.core.TableSpaceManager.executeStatement(TableSpaceManager.java:1020)
        at herddb.core.DBManager.executeStatement(DBManager.java:594)
        at herddb.core.DBManager.executePlan(DBManager.java:665)
        at herddb.server.ServerSideConnectionPeer.handleExecuteStatement(ServerSideConnectionPeer.java:638)
        at herddb.server.ServerSideConnectionPeer.requestReceived(ServerSideConnectionPeer.java:139)
        at herddb.network.netty.NettyChannel.lambda$requestReceived$0(NettyChannel.java:94)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by diegosalvi** [comment]
It was caused due to an issue on byte arrays comparison in java9+ (Java8 imlpementation was correctly an unsigned comparison Java9+ was signed)
