### ISSUE TITLE
Excessive DirectMemory allocation

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#326]
An user reported this error in a small testing EmailSuccess instance with MaxDirectMemory = 1g, running with HerdDB 0.8.1

```
19-01-21-13-09-40       herddb.cluster.BookkeeperCommitLog Jan 21, 2019 1:09:40 PM herddb.cluster.BookkeeperCommitLog$CommitFileWriter writeNoop
SEVERE: error
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16 777 216 byte(s) of direct memory (used: 1073741824, max: 1073741824)
        at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:640)
        at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:594)
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:214)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
        at herddb.log.LogEntry.serializeAsByteBuf(LogEntry.java:90)
        at herddb.cluster.BookkeeperCommitLog$CommitFileWriter.writeEntry(BookkeeperCommitLog.java:139)
        at herddb.cluster.BookkeeperCommitLog.log(BookkeeperCommitLog.java:251)
        at herddb.cluster.BookkeeperCommitLog$CommitFileWriter.writeNoop(BookkeeperCommitLog.java:179)
        at herddb.cluster.BookkeeperCommitLog$CommitFileWriter.access$000(BookkeeperCommitLog.java:111)
        at herddb.cluster.BookkeeperCommitLog.forceLastAddConfirmed(BookkeeperCommitLog.java:106)
        at herddb.cluster.BookkeeperCommitLogManager.lambda$forceLastAddConfirmed$0(BookkeeperCommitLogManager.java:98)
        at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4772)
        at herddb.cluster.BookkeeperCommitLogManager.forceLastAddConfirmed(BookkeeperCommitLogManager.java:97)
        at herddb.cluster.BookkeeperCommitLogManager.lambda$start$1(BookkeeperCommitLogManager.java:112)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)


```

**Comment by eolivelli** [comment]
I have suggested to add -Dio.netty.leakDetection.level=advanced in order to see if it is a leak or simply in that system you need to add more direct memory

cc @aluccaroni  @diegosalvi

**Comment by eolivelli** [comment]
4 leak records were discarded because the leak record count is targeted to 4. Use system property io.netty.leakDetection.targetRecords to increase the limit.
19-01-21-15-21-11       LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
#1:
        org.apache.bookkeeper.client.LedgerHandle.asyncAddEntry(LedgerHandle.java:996)
        herddb.cluster.BookkeeperCommitLog$CommitFileWriter.writeEntry(BookkeeperCommitLog.java:141)
        herddb.cluster.BookkeeperCommitLog.log(BookkeeperCommitLog.java:251)
        herddb.core.TableManager$6.accept(TableManager.java:1009)
        herddb.core.TableManager$1RecordProcessor.accept(TableManager.java:2568)
        herddb.core.TableManager.accessTableData(TableManager.java:2597)
        herddb.core.TableManager.executeUpdateAsync(TableManager.java:982)
        herddb.core.TableManager.executeStatementAsync(TableManager.java:509)
        herddb.core.TableSpaceManager.executeTableAwareStatement(TableSpaceManager.java:1169)
        herddb.core.TableSpaceManager.executeStatementAsyncInternal(TableSpaceManager.java:1073)
        herddb.core.TableSpaceManager.executeStatementAsync(TableSpaceManager.java:1053)
        herddb.core.DBManager.executeStatementAsync(DBManager.java:634)
        herddb.core.DBManager.executePlanAsync(DBManager.java:691)
        herddb.server.ServerSideConnectionPeer.handleExecuteStatement(ServerSideConnectionPeer.java:713)
        herddb.server.ServerSideConnectionPeer.requestReceived(ServerSideConnectionPeer.java:140)
        herddb.network.netty.NettyChannel.lambda$handlePduRequest$0(NettyChannel.java:93)
        java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        java.base/java.lang.Thread.run(Thread.java:834)
#2:
        io.netty.buffer.AdvancedLeakAwareByteBuf.writeBytes(AdvancedLeakAwareByteBuf.java:616)
        io.netty.buffer.ByteBufOutputStream.write(ByteBufOutputStream.java:68)
        java.base/java.io.DataOutputStream.write(DataOutputStream.java:107)
        java.base/java.io.FilterOutputStream.write(FilterOutputStream.java:108)
        herddb.utils.ExtendedDataOutputStream.writeArray(ExtendedDataOutputStream.java:127)
        herddb.log.LogEntry.serialize(LogEntry.java:115)
        herddb.log.LogEntry.serializeAsByteBuf(LogEntry.java:93)
        herddb.cluster.BookkeeperCommitLog$CommitFileWriter.writeEntry(BookkeeperCommitLog.java:139)
        herddb.cluster.BookkeeperCommitLog.log(BookkeeperCommitLog.java:251)
        herddb.core.TableManager$6.accept(TableManager.java:1009)
        herddb.core.TableManager$1RecordProcessor.accept(TableManager.java:2568)

**Comment by eolivelli** [comment]
@diegosalvi  @aluccaroni it seems the problem  is not on HerdDB, the user reported it has BookKeeper 4.7.2 on the classpath, which is not compatible with HerdDB 0.8.x which works ONLY with BookKeeper 4.8+

**Comment by eolivelli** [comment]
Thanks to  @sijie and @ivankelly for helping !

**Comment by diegosalvi** [comment]
Could be possible to detect bk classpath version?

Il giorno mar 22 gen 2019, 10:48 Enrico Olivelli <notifications@github.com>
ha scritto:

**Comment by eolivelli** [comment]
@diegosalvi  there is no way and IMHO it is not a safe way of working.
We should only have to take care of correct packaging.
The weird fact is that BK 4.8 is not binary compatbile with BK 4.7 in some APIs like the BookKeeperAdmin  API or the ensamble placement policy, so in theory the system should not have been started early (like with some NoSuchMethod error)
