### ISSUE TITLE
YCSB hangs due to long checkpoint

### ISSUE THREAD

**Issue by hamadodene** [diennea/herddb#330]
stacktrace --> [server.service.log](https://github.com/diennea/herddb/files/2836305/server.service.log)

Herd version --> 0.6.0, 0.8.0 and current master 0.9.0 
```
**Setenv conf:** 
-Xmx8g
-Xms8g 
-XX:MaxDirectMemorySize=4g   
```

**server properties:** 
```
server.memory.data.limit=100000000 -->100mb
server.memory.pk.limit=100000000 ---> 100mb

```
**ycsb workload conf** 

```
recordcount=1000000
operationcount=1000000
workload=com.yahoo.ycsb.workloads.CoreWorkload
readallfields=true
readproportion=0.5
updateproportion=0.5
scanproportion=0
insertproportion=0
requestdistribution=zipfian

```

**Comment by eolivelli** [comment]
@hamadodene reported the stacktrace during the problem, it seems that as we have very little memory the checkpoint needs to swapin/swap out pages of the PK, and this is very slow.
The system seems not blocked, only very slow

```
"hdb-toro-activator" #16 daemon prio=5 os_prio=0 cpu=68085.01ms elapsed=974.69s tid=0x00007f2385544800 nid=0x79bb runnable  [0x00007f234c8b4000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.String.length(java.base@11/String.java:658)
	at sun.nio.fs.UnixPath.normalizeAndCheck(java.base@11/UnixPath.java:75)
	at sun.nio.fs.UnixPath.<init>(java.base@11/UnixPath.java:69)
	at sun.nio.fs.UnixFileSystem.getPath(java.base@11/UnixFileSystem.java:280)
	at java.nio.file.Path.resolve(java.base@11/Path.java:515)
	at herddb.file.FileDataStorageManager.getPageFile(FileDataStorageManager.java:227)
	at herddb.file.FileDataStorageManager.readIndexPage(FileDataStorageManager.java:363)
	at herddb.index.blink.BLinkKeyToPageIndex$BLinkIndexDataStorageImpl.loadPage(BLinkKeyToPageIndex.java:542)
	at herddb.index.blink.BLinkKeyToPageIndex$BLinkIndexDataStorageImpl.loadLeafPage(BLinkKeyToPageIndex.java:537)
	at herddb.index.blink.BLink$Node.readLeafPage(BLink.java:2609)
	at herddb.index.blink.BLink$Node.readPage(BLink.java:2572)
	at herddb.index.blink.BLink$Node.loadAndLock(BLink.java:2305)
	at herddb.index.blink.BLink$Node.add_key(BLink.java:2023)
	at herddb.index.blink.BLink.insert(BLink.java:578)
	at herddb.index.blink.BLinkKeyToPageIndex.put(BLinkKeyToPageIndex.java:124)
	at herddb.core.TableManager.createImmutablePage(TableManager.java:574)
	at herddb.core.TableManager.checkpoint(TableManager.java:2082)
	at herddb.core.TableManager.checkpoint(TableManager.java:1908)
	at herddb.core.TableSpaceManager.checkpoint(TableSpaceManager.java:1565)
	at herddb.core.DBManager.checkpoint(DBManager.java:844)
	at herddb.core.DBManager.executeActivator(DBManager.java:1091)
	at herddb.core.DBManager.access$500(DBManager.java:114)
	at herddb.core.DBManager$Activator.run(DBManager.java:1028)
	at java.lang.Thread.run(java.base@11/Thread.java:834)
```

cc @diegosalvi FYI

I suggest @hamadodene to reduce the checkpoint period in order to have smaller checkpoints

**Comment by hamadodene** [comment]
I reduce checkpoint period from default conf to: 
```
server.checkpoint.period=300000  --> 5 min 
server.checkpoint.duration=60000 --> 1 min 
```
and it worked.

**Comment by eolivelli** [comment]
@hamadodene  
we have committed a few improvements during last days, but
@diegosalvi  is working to the last task

please check again once @diegosalvi commits the latest patch (still not public on github)

**Comment by diegosalvi** [comment]
I'm confident that this issue can be addressed by latest improvement in checkpoint operations and referenced PR #349 to provide a clean limit to the time used for checkpoint cleanup and compaction

**Comment by hamadodene** [comment]
After the modifications made by @diegosalvi , the problem is no longer present.
I close the issue.
Great Work @diegosalvi
