### ISSUE TITLE
BRIN corruption upon shutdown

### ISSUE THREAD

**Issue by diegosalvi** [diennea/herddb#405]
Bug

After a "bad" shutdown (kill -9) HerdDB standalone couldn't boot up a tablespace anymore.

There was a corruption problem on a BRIN index which blocked tablespace boot.

```
19-07-01-10-25-17       herddb.core.DBManager Jul 01, 2019 10:25:17 AM herddb.core.DBManager handleTableSpace
SEVERE: Error Booting tablespace mytablespace on vitello

19-07-01-10-25-17       herddb.core.DBManager Jul 01, 2019 10:25:17 AM herddb.core.DBManager handleTableSpace
SEVERE: Error
herddb.storage.DataStorageManagerException: Wrong next block, expected 145 but 806 found
        at herddb.index.brin.BlockRangeIndex.boot(BlockRangeIndex.java:1024)
        at herddb.index.brin.BRINIndexManager.doStart(BRINIndexManager.java:267)
        at herddb.core.AbstractIndexManager.start(AbstractIndexManager.java:88)
        at herddb.core.TableSpaceManager.bootIndex(TableSpaceManager.java:1468)
        at herddb.core.TableSpaceManager.recover(TableSpaceManager.java:263)
        at herddb.core.TableSpaceManager.start(TableSpaceManager.java:230)
        at herddb.core.DBManager.handleTableSpace(DBManager.java:526)
        at herddb.core.DBManager.manageTableSpaces(DBManager.java:1128)
        at herddb.core.DBManager.executeActivator(DBManager.java:1083)
        at herddb.core.DBManager.access$500(DBManager.java:114)
        at herddb.core.DBManager$Activator.run(DBManager.java:1031)
        at java.base/java.lang.Thread.run(Thread.java:834)


19-07-01-10-25-17       herddb.core.DBManager Jul 01, 2019 10:25:17 AM herddb.core.DBManager manageTableSpaces
SEVERE: cannot handle tablespace mytablespace
```

Data contained in block metadata and in block data differed (ids 145 vs 806) and Herd refused to boot up the tablespace.

The tablespace itself can be started again manually deleting corrupted indexes (Herd will rebuid them on boot) but such corruption shouldn't happen.

**Comment by eolivelli** [comment]
@diegosalvi did you keep the corrupted db? 
Otherwise we will have to try to reproduce the issue with a static analysis of code or with some hammer test.
Logs will be helpful as well.
I guess it is a checkpoint problem or a recovery related one
