### ISSUE TITLE
NPE on setPageDirty

### ISSUE THREAD

**Issue by diegosalvi** [diennea/herddb#426]
**BUG REPORT**

Got a NPE on a clean installed standalone HerdDB

```
WARNING: Exception while updating message status: java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
        at herddb.core.PageSet.setPageDirty(PageSet.java:109)
        at herddb.core.PageSet.setPageDirty(PageSet.java:119)
        at herddb.core.TableManager.applyUpdate(TableManager.java:1675)
        at herddb.core.TableManager.onTransactionCommit(TableManager.java:1413)
        at herddb.core.TableSpaceManager.apply(TableSpaceManager.java:361)
        at herddb.core.TableSpaceManager.lambda$commitTransaction$16(TableSpaceManager.java:1692)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
        ... 5 more
```

**Comment by diegosalvi** [comment]
It appear that selected page isn't listed in PageSet.activePages:
* or PK returned a wrong unexisting page
* or the page wasn't added to active pages but it should have been added
* or the page was removed from active pages but it souldn't
