### ISSUE TITLE
Recovery error while using BookKeeper

### ISSUE THREAD

**Issue by diegosalvi** [diennea/herddb#458]
**BUG REPORT**

1. Please describe the issue you observed:

During recovery on a cluster environment (with BK) transaction recovery fails over and over.
```
19-09-04-13-51-17       herddb.core.DBManager Sep 04, 2019 1:51:17 PM herddb.core.DBManager manageTableSpaces
SEVERE: cannot handle tablespace q1
herddb.log.LogNotAvailableException: java.lang.IllegalStateException: Corrupted transaction, syncing on a position smaller than transaction last sequence number
        at herddb.cluster.BookkeeperCommitLog.recovery(BookkeeperCommitLog.java:486)
        at herddb.core.TableSpaceManager.recover(TableSpaceManager.java:295)
        at herddb.core.TableSpaceManager.start(TableSpaceManager.java:232)
        at herddb.core.DBManager.handleTableSpace(DBManager.java:535)
        at herddb.core.DBManager.manageTableSpaces(DBManager.java:1107)
        at herddb.core.DBManager.executeActivator(DBManager.java:1057)
        at herddb.core.DBManager.access$500(DBManager.java:115)
        at herddb.core.DBManager$Activator.run(DBManager.java:1005)
        at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.IllegalStateException: Corrupted transaction, syncing on a position smaller than transaction last sequence number
        at herddb.model.Transaction.sync(Transaction.java:566)
        at herddb.core.TableSpaceManager.apply(TableSpaceManager.java:360)
        at herddb.core.TableSpaceManager$ApplyEntryOnRecovery.accept(TableSpaceManager.java:1815)
        at herddb.core.TableSpaceManager$ApplyEntryOnRecovery.accept(TableSpaceManager.java:1807)
        at herddb.cluster.BookkeeperCommitLog.recovery(BookkeeperCommitLog.java:454)
        ... 8 more
```

- What did you do?
Just shut down and restarted whole HerdDB cluster and BKs

- What did you expect to see?
I was expecting the recovery working

- What did you see instead?
Fails to recover the state from transaction log

**Comment by eolivelli** [comment]
The error is on 0.11.9 (best guess).
In that version in that point of code we are recovering a Commit Transaction entry.
Unfortunately there is not much information.

The code with the problem has nothing to do with BookKeeper or replication, the same case may happen in standalone mode because.
```
TableSpaceManager#ApplyEntryOnRecovery:
apply(new CommitLogResult(t, false, true), u, true);
```

We have to see the correct sequence of entries on the log.
I guess it is a transaction that was partially stored in a snapshot and partially stored on the WAL

**Comment by diegosalvi** [comment]
The version was a 0.12.0-SNAPSHOT

**Comment by eolivelli** [comment]
No man.
Check the line numbers

**Comment by eolivelli** [comment]
I have added a test case in #460, the test reproduces a difference in behaviour during recovery in BooKeeperCommitLog vs FileCommitLog, as in BookKeeperCommitLog log entries for transaction are logged without waiting an ack from BK so the lastSequenceNumber of Transaction is not updated.

But I can't find a way to break it

**Comment by aluccaroni** [comment]
@diegosalvi this issue is still relevant?
