### ISSUE TITLE
Checkpoint stop running after IllegalMonitorStateException

### ISSUE THREAD

**Issue by aluccaroni** [diennea/herddb#476]
**BUG REPORT**

1. Please describe the issue you observed:

We got a very slow startup on an HerdDB single istance (v0.12.0). Looking at the stacktrace we saw that it was replaying a lot of transaction from the WAL (~4.8GB of files inside the txlog).

Looking around we found out that the Checkpoint wasn't running since 7 days ago, during the last Checkpoint we saw this error:

```
19-09-19-23-42-45       herddb.core.TableSpaceManager Sep 19, 2019 11:42:45 PM herddb.core.TableSpaceManager checkpoint
INFO: gallina checkpoint finish herd started ad (400,163687), finished at (400,163687), total time 1552 ms

19-09-19-23-46-28       herddb.core.DBManager Sep 19, 2019 11:46:28 PM herddb.core.DBManager$Activator run
SEVERE: fatal activator erro
java.lang.IllegalMonitorStateException
        at java.base/java.util.concurrent.locks.StampedLock.unlockRead(StampedLock.java:708)
        at herddb.utils.LocalLockManager.releaseReadLock(LocalLockManager.java:146)
        at herddb.utils.LocalLockManager.releaseLock(LocalLockManager.java:158)
        at herddb.model.Transaction.releaseLocksOnTable(Transaction.java:211)
        at herddb.core.TableManager.onTransactionRollback(TableManager.java:1488)
        at herddb.core.TableSpaceManager.apply(TableSpaceManager.java:347)
        at herddb.core.TableSpaceManager.forceTransactionRollback(TableSpaceManager.java:1027)
        at herddb.core.TableSpaceManager.processAbandonedTransactions(TableSpaceManager.java:730)
        at herddb.core.DBManager.executeActivator(DBManager.java:1082)
        at herddb.core.DBManager.access$500(DBManager.java:115)
        at herddb.core.DBManager$Activator.run(DBManager.java:1005)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

We need to handle this error case and, also, have a way to monitor if the Checkpoint don't run for too many time.

**Comment by diegosalvi** [comment]
Looking from the trace it seems that activator thread died on error thus it
didn't run checkpoints anymore. We should both fix abandoned transactions
check and prorect activator thread from such exits (or start it again... )

Il gio 26 set 2019, 11:28 Alessandro Luccaroni <notifications@github.com>
ha scritto:

**Comment by eolivelli** [comment]
Fix available in #47 
we should cherry pick to stable branch 0.12 and eventually cut a new release
