### ISSUE TITLE
SystemTablesTest is flaky - maybe an error on system tables

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#480]
During a precommit build I saw this error:

```
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 7.596 s <<< FAILURE! - in herddb.core.SystemTablesTest
[ERROR] testSysTables(herddb.core.SystemTablesTest)  Time elapsed: 5.039 s  <<< ERROR!
herddb.model.StatementExecutionException: java.lang.StringIndexOutOfBoundsException: offset 43, count 102, length 47
	at herddb.core.DBManager.executePlan(DBManager.java:686)
	at herddb.core.TestUtils.scan(TestUtils.java:71)
	at herddb.core.SystemTablesTest.testSysTables(SystemTablesTest.java:80)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.StringIndexOutOfBoundsException: offset 43, count 102, length 47
	at java.base/java.lang.String.checkBoundsOffCount(String.java:3304)
	at java.base/java.lang.String.<init>(String.java:505)
	at herddb.utils.RawString.toString(RawString.java:160)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
	at herddb.utils.SQLRecordPredicateFunctions.compare(SQLRecordPredicateFunctions.java:98)
	at herddb.codec.RecordSerializer.compareDeserializeTypeAndValue(RecordSerializer.java:255)
	at herddb.codec.RecordSerializer.compareRawDataFromValue(RecordSerializer.java:699)
	at herddb.codec.DataAccessorForFullRecord.fieldEqualsTo(DataAccessorForFullRecord.java:78)
	at herddb.sql.expressions.AccessCurrentRowExpression.opEqualsTo(AccessCurrentRowExpression.java:49)
	at herddb.sql.expressions.CompiledEqualsExpression.evaluate(CompiledEqualsExpression.java:42)
	at herddb.sql.SQLRecordPredicate.evaluate(SQLRecordPredicate.java:110)
	at herddb.core.system.AbstractSystemTableManager.lambda$scan$0(AbstractSystemTableManager.java:250)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at herddb.core.system.AbstractSystemTableManager.scan(AbstractSystemTableManager.java:254)
	at herddb.core.TableSpaceManager.scan(TableSpaceManager.java:562)
	at herddb.core.DBManager.scan(DBManager.java:732)
	at herddb.core.DBManager.executePlanAsync(DBManager.java:698)
	at herddb.core.DBManager.executePlan(DBManager.java:675)
	... 27 more

```

**Comment by eolivelli** [comment]
I can't reproduce the issue locally, even leaving an infinte loop

Unfortunately the error is thrown while throwing:
```
throw new IllegalArgumentException(
                "uncomparable objects " + a.getClass() + " ('" + a + "') vs " + b.getClass() + " ('" + b + ")"); 
```
So maybe the real reason is hidden.

There is a simple query on systables TABLE
`SELECT * FROM systables where systemtable=true`

**Comment by aluccaroni** [comment]
@eolivelli  can we close this issue?

**Comment by eolivelli** [comment]
No, sometimes it still happens

**Comment by eolivelli** [comment]
Another error:
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.907 s <<< FAILURE! - in herddb.core.SystemTablesTest
[ERROR] testSysTables(herddb.core.SystemTablesTest)  Time elapsed: 3.759 s  <<< ERROR!
herddb.model.StatementExecutionException: java.lang.StringIndexOutOfBoundsException: offset 43, count 102, length 47
	at herddb.core.DBManager.executePlan(DBManager.java:686)
	at herddb.core.TestUtils.scan(TestUtils.java:71)
	at herddb.core.SystemTablesTest.testSysTables(SystemTablesTest.java:68)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.StringIndexOutOfBoundsException: offset 43, count 102, length 47
	at java.base/java.lang.String.checkBoundsOffCount(String.java:3304)
	at java.base/java.lang.String.<init>(String.java:505)
	at herddb.utils.RawString.toString(RawString.java:160)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
	at herddb.utils.SQLRecordPredicateFunctions.compare(SQLRecordPredicateFunctions.java:98)
	at herddb.codec.RecordSerializer.compareDeserializeTypeAndValue(RecordSerializer.java:255)
	at herddb.codec.RecordSerializer.compareRawDataFromValue(RecordSerializer.java:699)
	at herddb.codec.DataAccessorForFullRecord.fieldEqualsTo(DataAccessorForFullRecord.java:78)
	at herddb.sql.expressions.AccessCurrentRowExpression.opEqualsTo(AccessCurrentRowExpression.java:49)
	at herddb.sql.expressions.CompiledEqualsExpression.evaluate(CompiledEqualsExpression.java:42)
	at herddb.sql.SQLRecordPredicate.evaluate(SQLRecordPredicate.java:103)
	at herddb.core.system.AbstractSystemTableManager.lambda$scan$0(AbstractSystemTableManager.java:250)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at herddb.core.system.AbstractSystemTableManager.scan(AbstractSystemTableManager.java:254)
	at herddb.core.TableSpaceManager.scan(TableSpaceManager.java:562)
	at herddb.core.DBManager.scan(DBManager.java:732)
	at herddb.core.DBManager.executePlanAsync(DBManager.java:698)
	at herddb.core.DBManager.executePlan(DBManager.java:675)
	... 27 more
