### ISSUE TITLE
Error with truncate table + index

### ISSUE THREAD

**Issue by diegosalvi** [diennea/herddb#489]
**BUG REPORT**

1. Please describe the issue you observed:
Error while truncating a table with a secondary index and existing data

- What did you do?
Table truncate

- What did you expect to see?
The table truncated

- What did you see instead?
```
ERROR:java.sql.SQLException: herddb.core.HerdDBInternalException: herddb.model.StatementExecutionException: internal data error: herddb.storage.DataStorageManagerException: java.io.IOException: herddb.storage.DataStorageManagerException: java.nio.file.NoSuchFileException: /home/root/*****/dbdata/data/7505a889a4c0432e870edf97946f1c2c.tablespace/543624a9-887f-445b-8a6f-698481767c19.index/2.page
        at herddb.core.TableManager.lambda$executeStatementAsync$1(TableManager.java:581)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
        at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
        at herddb.core.TableManager.executeStatementAsync(TableManager.java:576)
        at herddb.core.TableSpaceManager.executeTableAwareStatement(TableSpaceManager.java:1226)
        at herddb.core.TableSpaceManager.executeStatementAsyncInternal(TableSpaceManager.java:1122)
        at herddb.core.TableSpaceManager.executeStatementAsync(TableSpaceManager.java:1092)
        at herddb.core.DBManager.executeStatementAsync(DBManager.java:648)
        at herddb.core.DBManager.executePlanAsync(DBManager.java:705)
        at herddb.server.ServerSideConnectionPeer.handleExecuteStatement(ServerSideConnectionPeer.java:721)
        at herddb.server.ServerSideConnectionPeer.requestReceived(ServerSideConnectionPeer.java:138)
        at herddb.network.netty.NettyChannel.lambda$handlePduRequest$0(NettyChannel.java:96)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: herddb.model.StatementExecutionException: internal data error: herddb.storage.DataStorageManagerException: java.io.IOException: herddb.storage.DataStorageManagerException: java.nio.file.NoSuchFileException: /home/root/****/dbdata/data/7505a889a4c0432e870edf97946f1c2c.tablespace/543624a9-887f-445b-8a6f-698481767c19.index/2.page
        ... 19 more
Caused by: herddb.storage.DataStorageManagerException: java.io.IOException: herddb.storage.DataStorageManagerException: java.nio.file.NoSuchFileException: /home/root/****/dbdata/data/7505a889a4c0432e870edf97946f1c2c.tablespace/543624a9-887f-445b-8a6f-698481767c19.index/2.page
        at herddb.index.brin.BRINIndexManager.checkpoint(BRINIndexManager.java:369)
        at herddb.core.TableManager.checkpoint(TableManager.java:2756)
        at herddb.core.TableManager.checkpoint(TableManager.java:2180)
        at herddb.core.TableManager.flush(TableManager.java:1992)
        at herddb.core.TableManager.lambda$executeStatementAsync$1(TableManager.java:579)
        ... 18 more
Caused by: java.io.IOException: herddb.storage.DataStorageManagerException: java.nio.file.NoSuchFileException: /home/root/****/dbdata/data/7505a889a4c0432e870edf97946f1c2c.tablespace/543624a9-887f-445b-8a6f-698481767c19.index/2.page
        at herddb.index.brin.BRINIndexManager$IndexDataStorageImpl.createDataPage(BRINIndexManager.java:474)
        at herddb.index.brin.BlockRangeIndex$Block.checkpointNoLock(BlockRangeIndex.java:665)
        at herddb.index.brin.BlockRangeIndex$Block.checkpoint(BlockRangeIndex.java:679)
        at herddb.index.brin.BlockRangeIndex$Block.access$800(BlockRangeIndex.java:220)
        at herddb.index.brin.BlockRangeIndex.merge(BlockRangeIndex.java:760)
        at herddb.index.brin.BlockRangeIndex.checkpoint(BlockRangeIndex.java:980)
        at herddb.index.brin.BRINIndexManager.checkpoint(BRINIndexManager.java:310)
        ... 22 more
Caused by: herddb.storage.DataStorageManagerException: java.nio.file.NoSuchFileException: /home/root/****/dbdata/data/7505a889a4c0432e870edf97946f1c2c.tablespace/543624a9-887f-445b-8a6f-698481767c19.index/2.page
        at herddb.file.FileDataStorageManager.writeIndexPage(FileDataStorageManager.java:947)
        at herddb.index.brin.BRINIndexManager$IndexDataStorageImpl.createDataPage(BRINIndexManager.java:470)
        ... 28 more
Caused by: java.nio.file.NoSuchFileException: /home/root/****/dbdata/data/7505a889a4c0432e870edf97946f1c2c.tablespace/543624a9-887f-445b-8a6f-698481767c19.index/2.page
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:178)
        at java.base/java.nio.channels.FileChannel.open(FileChannel.java:292)
        at java.base/java.nio.channels.FileChannel.open(FileChannel.java:345)
        at herddb.utils.ManagedFile.open(ManagedFile.java:79)
        at herddb.file.FileDataStorageManager.writeIndexPage(FileDataStorageManager.java:938)
        ... 29 more
```

**Comment by aluccaroni** [comment]
Below some steps to reproduce. Please note that after the TRUNCATE error if I restart the server HERD will not come UP again with a very similar error (herddb.storage.DataStorageManagerException: java.io.IOException: herddb.storage.DataStorageManagerException: java.nio.file.NoSuchFileException: /tmp/herd/herddb-services-0.12.2/dbdata/data/c456e79617034cf68042758173d94edd.tablespace/f565fbb7-19da-4d51-a156-07a18489eb7a.index/1.page)

```
CREATE TABLESPACE 'q1'
CREATE TABLE q1.q1_feedback1 (  FEEDBACK_ID   BIGINT       NOT NULL FEEDBACK_ID,  STORE_ID      VARCHAR(512) NULL,  MSG_ID        BIGINT       NOT NULL,  FEEDBACK_TYPE TINYINT      NOT NULL,  RECEIVE_TIME  TIMESTAMP    /* NOT NULL */,  RETURN_PATH   VARCHAR(512) NOT NULL,  HELO          VARCHAR(255) NULL,  IP            VARCHAR(15)  NULL) 
CREATE INDEX q1_FEEDBACK_SEARCH_BY_MSG_ID1 ON q1.q1_feedback1(MSG_ID)
INSERT INTO q1.q1_feedback1 values (1,'char',1,1,null,'char','char','char',1)
TRUNCATE TABLE q1.q1_feedback1
```
