### ISSUE TITLE
JdbcDriverZookeeperTest isflaky on Jenkins

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#494]
The JdbcDriverZookeeperTest test is very flaky on Jenkins, we should make it more lenient to low CPU peaks

org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
	at org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase.waitForConnection(ZooKeeperWatcherBase.java:159)
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$Builder.build(ZooKeeperClient.java:257)
	at herddb.utils.ZKTestEnv.startBookie(ZKTestEnv.java:76)
	at herddb.utils.ZKTestEnv.startBookie(ZKTestEnv.java:44)
	at herddb.jdbc.JdbcDriverZookeeperTest.beforeSetup(JdbcDriverZookeeperTest.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:

**Comment by eolivelli** [comment]
I am going to fix this issue, it is too annoying

**Comment by eolivelli** [comment]
@TisonKun unfortunately the error did not go away :-(

https://dev.majordodo.org/jenkins/job/HerdDB_012/51/org.herddb$herddb-jdbc/testReport/herddb.jdbc/JdbcDriverZookeeperTest/test/
