### ISSUE TITLE
Calcite - CLI - case sensitivy

### ISSUE THREAD

**Issue by aluccaroni** [diennea/herddb#497]
**BUG REPORT**

1. Please describe the issue you observed:

It seems that we have some issue with the CLI parser (Calcite?) with case sensitivity.
See also https://github.com/diennea/herddb/pull/495.

In particular if I create a TABLE with a mix of upper and lowercase chars, then I'm unable to use the command "SHOW CREATE TABLE".

` CREATE TABLE mytablespace.q1_additional_info(msg_id long not null,sid integer not null,name string not null,value string not null,PRIMARY KEY(msg_id,sid,name))`

```
SHOW CREATE TABLE mytablespace.teSt10
Executing query:SHOW CREATE TABLE mytablespace.teSt10
ERROR:java.sql.SQLException: herddb.model.TableDoesNotExistException: Table teSt10 does not exist.
        at herddb.sql.CalcitePlanner.calculateShowCreateTable(CalcitePlanner.java:379)
        at herddb.sql.CalcitePlanner.translate(CalcitePlanner.java:287)
        at herddb.server.ServerSideConnectionPeer.handleOpenScanner(ServerSideConnectionPeer.java:445)
        at herddb.server.ServerSideConnectionPeer.requestReceived(ServerSideConnectionPeer.java:181)
        at herddb.network.netty.NettyChannel.lambda$handlePduRequest$0(NettyChannel.java:96)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

A part from fixing the issue at hand we need to check case sensitivity for all the CLI commands (I expect other commands to have problems).

**Comment by amitvc** [comment]
@aluccaroni @eolivelli I will look into this tonight.

**Comment by amitvc** [comment]
@aluccaroni @eolivelli Many places in our code we assume the query would be in upper case. 
For example query we expect is "SHOW CREATE ..". If instead we get "show create .." then we won't even recognize it as valid query. Should we look into accepting SQL queries in both upper and lower case?
The current issue with this ticket is the table name gets converted to lower case during creation. I need to apply the same fix during the show create table query execution as well.

**Comment by amitvc** [comment]
Also if the user creates a table with upper case or mix of upper and lower case what should we do? Is our convention now to convert table, tablespace and column names to lower case?

**Comment by eolivelli** [comment]
As far as queries (SELECT, UPDATE) work we can do whatever we want.
For instance as far as I know Oracle converts all ids to uppercase.
Converting ids found in DDL works for me

**Comment by aluccaroni** [comment]
I've seen many time in mysql the usage of the option lower_case_table_names=1 for this specific problem (also, there is an additional issue related to different case sensitivity support on windows vs *nix) so I'm OK with converting to lowercase

**Comment by amitvc** [comment]
@eolivelli @aluccaroni Starting back conversation on this ticket. Some use case - 

- If a user creates a table in all lower case : 
e.g create table test(name string primary key,age int,address string). All column names and table names are lower case
Then from CLI they query select * from Test or select * from test where Age > 20 or select * from 
TEST where age =20
What should be the expected behavior?

**Comment by eolivelli** [comment]
I would fix the issue as first task

**Comment by amitvc** [comment]
@eolivelli This is a simple fix. I am testing it right now. I also see problem with commands from CLI if they are lower case the code expects them to be upper case. Some thoughts around it ?

**Comment by eolivelli** [comment]
We should handle all of the commands in a case non sensitive way :-)

**Comment by eolivelli** [comment]
@amitvc did you have time to check this issue ?
we have fixed a few cases about ALTER TABLE but maybe SHOW CREATE is still not working properly

**Comment by eolivelli** [comment]
@aluccaroni @amitvc it this issue fixed ?

**Comment by aluccaroni** [comment]
@eolivelli I've just tried with v0.18 and it doesn't seem to be fixed. At least now we don't print the full stacktrace:

```
herddb(herd): CREATE TABLE mytablespace.teSt10(msg_id long not null,sid integer not null,name string not null,value string not null,PRIMARY KEY(msg_id,sid,name))
herddb(mytablespace): SHOW CREATE TABLE mytablespace.teSt10
Error: Table teSt10 does not exist.
```

```
herddb(mytablespace): SELECT * FROM SYSTABLES

| tablespace   | table_name                | table_uuid                           | systemtable |
| ----------   | ----------                | ----------                           | ----------- |
| herd         | syscolumns                | 78e55881-35eb-4de8-98ea-f22807e07077 | true        |
| herd         | sysindexcolumns           | 5e1d8fe6-7cb9-496e-9ac2-a72fb73e31ca | true        |
| herd         | sysindexes                | beb05505-42c2-4733-a1ed-e8d2ee6eab56 | true        |
| herd         | syslogstatus              | 1d08e755-9430-463d-9b3e-538bfde7dd0f | true        |
| herd         | sysnodes                  | fbecc005-f246-421f-83bb-c711959fb2fa | true        |
| herd         | sysstatements             | 70d1b5e7-8bd6-447d-a3a9-89aa02f90cb1 | true        |
| herd         | systables                 | 498c7491-fb2c-47ee-9b63-55ea291e72ad | true        |
| herd         | systablespacereplicastate | c2061010-bfcd-43b4-ab7f-fb222d62fddb | true        |
| herd         | systablespaces            | 19c36d39-4c88-4cce-a18f-f8c50fb1478e | true        |
| herd         | systablestats             | 678f104e-66af-4e93-9c0a-f93b29302c6f | true        |
| herd         | systransactions           | 9d3e6021-f132-4c9c-9bf7-a812da46f630 | true        |
| mytablespace | test10                    | 3ee8c502-4069-4452-9780-0085cc0aa879 | false       |
```

The table is created as lowercase but, then, the "SHOW CREATE TABLE" command seems to still be case sensitive.

Please note that a simple select seems to be working fine:
```
herddb(mytablespace): SELECT * from mytablespace.teSt10

Empty results set
```

**Comment by amitvc** [comment]
@aluccaroni @eolivelli Is the goal to preserve the name as the user entered it or we want to make it lower or upper case?

**Comment by eolivelli** [comment]
table names should not be case sensitive.
so "SHOW CREATE TABLE foo" must work as well as "SHOW CREATE TABLE Foo"

probably we are missing some "toLowercase" o "toUppercase" in SHOW CREATE command handler

**Comment by amitvc** [comment]
@eolivelli Ok. Yes, I can fix it tonight. I will perform some tests and send a patch. The case-sensitivity is also a problem in other commands as well.

**Comment by amitvc** [comment]
@eolivelli This is still on my radar. Got busy at work. Hoping to get this patch out soon.

**Comment by eolivelli** [comment]
Good to know
thank you @amitvc

**Comment by eolivelli** [comment]
you could also take a look to pending Pull Requests, any eye on the patches is always really appreciated

**Comment by amitvc** [comment]
@eolivelli Sent a PR for this.
