### ISSUE TITLE
Bug of Byte type

### ISSUE THREAD

**Issue by AndreaDAng** [diennea/herddb#505]
There is an issue in the declaration of a Byte type variable during the creation of a new table.
The issue doesn't allow to create the table.

query: `create table tabrutta(p1 string, p2 byte, p3 int, p4 long, p5 float, p6 double, p7 timestamp, p8 blob)`

Error:
```
Executing query:create table tabrutta(p1 string, p2 byte, p3 int, p4 long, p5 float, p6 double, p7 timestamp, p8 blob)
ERROR:java.sql.SQLException: herddb.model.StatementExecutionException: bad type byte
        at herddb.sql.DDLSQLPlanner.sqlDataTypeToColumnType(DDLSQLPlanner.java:525)
        at herddb.sql.DDLSQLPlanner.buildCreateTableStatement(DDLSQLPlanner.java:311)
        at herddb.sql.DDLSQLPlanner.plan(DDLSQLPlanner.java:249)
        at herddb.sql.DDLSQLPlanner.translate(DDLSQLPlanner.java:224)
        at herddb.sql.CalcitePlanner.translate(CalcitePlanner.java:244)
        at herddb.server.ServerSideConnectionPeer.handleExecuteStatement(ServerSideConnectionPeer.java:706)
        at herddb.server.ServerSideConnectionPeer.requestReceived(ServerSideConnectionPeer.java:138)
        at herddb.network.netty.NettyChannel.lambda$handlePduRequest$0(NettyChannel.java:96)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by eolivelli** [comment]
@AndreaDAng what's your usecase ?
what do you expect to be a 'byte' ? and unsigned 1-byte integer ?
