### ISSUE TITLE
Try to disable Janino bytecode compiler - not used by HerdDB and very expensive

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#517]
Calcite uses Janino in order to generate Java bytecode for the execution of data access plans, we are not using this feature but we are paying the cost.
It would be better to have a way to disable Janino

```
This is an example of expensive work:
"main"
    at sun.security.provider.SHA2.lf_S(SHA2.java:155)
    at sun.security.provider.SHA2.lf_delta1(SHA2.java:191)
    at sun.security.provider.SHA2.implCompress0(SHA2.java:222)
    at sun.security.provider.SHA2.implCompress(SHA2.java:199)
    at sun.security.provider.DigestBase.implCompressMultiBlock0(DigestBase.java:150)
    at sun.security.provider.DigestBase.implCompressMultiBlock(DigestBase.java:144)
    at sun.security.provider.DigestBase.engineUpdate(DigestBase.java:131)
    at java.security.MessageDigest$Delegate.engineUpdate(MessageDigest.java:613)
    at java.security.MessageDigest.update(MessageDigest.java:345)
    at sun.security.util.ManifestEntryVerifier.update(ManifestEntryVerifier.java:173)
    at java.util.jar.JarVerifier.update(JarVerifier.java:227)
    at java.util.jar.JarVerifier$VerifierStream.read(JarVerifier.java:470)
    at jdk.internal.loader.Resource.getBytes(Resource.java:124)
    at jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:797)
    at jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
    at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
    at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
    at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:229)
    at org.codehaus.janino.SimpleCompiler.compileToClassLoader(SimpleCompiler.java:465)
    at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:216)
    at org.codehaus.janino.SimpleCompiler.cook(SimpleCompiler.java:207)
    at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:80)
    at org.codehaus.commons.compiler.Cookable.cook(Cookable.java:75)
    at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.compile(JaninoRelMetadataProvider.java:453)
    at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.load3(JaninoRelMetadataProvider.java:375)
    at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.lambda$static$0(JaninoRelMetadataProvider.java:109)
    at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider$$Lambda$280.436949795.apply
    at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:146)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
    at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
    at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.create(JaninoRelMetadataProvider.java:475)
    at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.revise(JaninoRelMetadataProvider.java:488)
    at org.apache.calcite.rel.metadata.RelMetadataQuery.revise(RelMetadataQuery.java:193)
    at org.apache.calcite.rel.metadata.RelMetadataQuery.collations(RelMetadataQuery.java:558)
    at org.apache.calcite.rel.metadata.RelMdCollation.project(RelMdCollation.java:250)
    at org.apache.calcite.rel.logical.LogicalProject.lambda$create$0(LogicalProject.java:111)
    at org.apache.calcite.rel.logical.LogicalProject$$Lambda$284.2083969860.get
    at org.apache.calcite.plan.RelTraitSet.replaceIfs(RelTraitSet.java:238)
    at org.apache.calcite.rel.logical.LogicalProject.create(LogicalProject.java:110)
    at org.apache.calcite.rel.logical.LogicalProject.create(LogicalProject.java:100)
    at org.apache.calcite.rel.core.RelFactories$ProjectFactoryImpl.createProject(RelFactories.java:145)
    at org.apache.calcite.tools.RelBuilder.project(RelBuilder.java:1267)
    at org.apache.calcite.tools.RelBuilder.projectNamed(RelBuilder.java:1323)
    at org.apache.calcite.sql2rel.SqlToRelConverter.createAggImpl(SqlToRelConverter.java:2809)
    at org.apache.calcite.sql2rel.SqlToRelConverter.convertAgg(SqlToRelConverter.java:2714)
    at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelectImpl(SqlToRelConverter.java:665)
    at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelect(SqlToRelConverter.java:627)
    at org.apache.calcite.sql2rel.SqlToRelConverter.convertQueryRecursive(SqlToRelConverter.java:3100)
    at org.apache.calcite.sql2rel.SqlToRelConverter.convertQuery(SqlToRelConverter.java:563)
    at org.apache.calcite.prepare.PlannerImpl.rel(PlannerImpl.java:235)
    at herddb.sql.CalcitePlanner.runPlanner(CalcitePlanner.java:506)
    at herddb.sql.CalcitePlanner.translate(CalcitePlanner.java:296)
    at herddb.core.TestUtils.scan(TestUtils.java:70)
    at herddb.core.BetterExecuteSyntaxTest.betterSyntax(BetterExecuteSyntaxTest.java:118)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:566)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
    at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by eolivelli** [comment]
This issue depends on 
https://github.com/apache/calcite/pull/1901
