### ISSUE TITLE
Graceful socket close during dumps

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#541]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

When a follower receives a tablespace dump it then closes the socket, leading to an ugly log on the server side.
Users reported this log as an error, but it is not

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

should-have

3. Provide any additional detail on your proposed use case for this feature.

Example of server-side log, in this case after a dump:

```
Jan 24, 2020 10:24:50 AM herddb.network.netty.NettyChannel lambda$failPendingMessages$5
SEVERE: NettyChannel{name=unnamed, id=35, socket=[id: 0x81e5b4c3, L:/10.168.1.209:7000 ! R:/10.168.1.209:51556] pending 1 msgs} message 28 was not replied callback:herddb.network.Channel$$Lambda$1273/0x00000008011a3c40@5303513b
Jan 24, 2020 10:24:50 AM herddb.server.ServerSideConnectionPeer channelClosed
INFO: channelClosed ServerSideConnectionPeer{id=35, channel=NettyChannel{name=unnamed, id=35, socket=[id: 0x81e5b4c3, L:/10.168.1.209:7000 ! R:/10.168.1.209:51556] pending 0 msgs}, address=/10.168.1.209:51556, username=sa}
Jan 24, 2020 10:24:50 AM herddb.core.TableSpaceManager dumpTableSpace
SEVERE: error sending dump id localhost:1
java.util.concurrent.TimeoutException: io-error while waiting for reply: java.io.IOException: comunication channel is closed. Cannot wait for pending messages, socket=[id: 0x81e5b4c3, L:/10.168.1.209:7000 ! R:/10.168.1.209:51556]
	at herddb.network.Channel.sendMessageWithPduReply(Channel.java:91)
	at herddb.core.TableSpaceManager.dumpTableSpace(TableSpaceManager.java:891)
	at herddb.core.DBManager.dumpTableSpace(DBManager.java:901)
	at herddb.server.ServerSideConnectionPeer.handleRequestTablespaceDump(ServerSideConnectionPeer.java:552)
	at herddb.server.ServerSideConnectionPeer.requestReceived(ServerSideConnectionPeer.java:206)
	at herddb.network.netty.NettyChannel.lambda$handlePduRequest$0(NettyChannel.java:96)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.io.IOException: comunication channel is closed. Cannot wait for pending messages, socket=[id: 0x81e5b4c3, L:/10.168.1.209:7000 ! R:/10.168.1.209:51556]
	at herddb.network.netty.NettyChannel.lambda$failPendingMessages$4(NettyChannel.java:247)
	... 6 more

Jan 24, 2020 10:24:50 AM herddb.core.TableSpaceManager dumpTableSpace
INFO: unPinTableCheckpoint 606f243fbab44d3488cb99904168fe4e.usertable (6656d8ea-c025-4fe7-b1d8-5dd43d7aa9e1) (0,200312)

```

Please note the line with **pending 1 msgs**

**Comment by eolivelli** [comment]
We can try to enhance the protocol or simply do not log the stacktrace, as this is the expected behaviour

**Comment by eolivelli** [comment]
Done in current master
