### ISSUE TITLE
Server cannot boot after issues a TABLESPACECONSISTENCY check

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#602]
It looks like that if I reboot a server after issuing the TABLESPACECONSISTENCY the server cannot boot anymore, stuck at this point.
The tablespace is not yet available, so Calcite planner cannot perform the query.
```


"hdb-qui-activator" #17 daemon prio=5 os_prio=0 cpu=425.34ms elapsed=52.87s tid=0x00007f7c51a26800 nid=0xb237 sleeping [0x00007f7b418e0000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(java.base@14/Native Method)
        at herddb.sql.CalcitePlanner.getSchemaForTableSpace(CalcitePlanner.java:441)
        at herddb.sql.CalcitePlanner.runPlanner(CalcitePlanner.java:504)
        at herddb.sql.CalcitePlanner.translate(CalcitePlanner.java:303)
        at herddb.core.TableSpaceManager.apply(TableSpaceManager.java:545)
        at herddb.core.TableSpaceManager$ApplyEntryOnRecovery.accept(TableSpaceManager.java:2071)
        at herddb.core.TableSpaceManager$ApplyEntryOnRecovery.accept(TableSpaceManager.java:2060)
        at herddb.cluster.BookkeeperCommitLog.recovery(BookkeeperCommitLog.java:624)
        at herddb.core.TableSpaceManager.recover(TableSpaceManager.java:316)
        at herddb.core.TableSpaceManager.start(TableSpaceManager.java:243)
        at herddb.core.DBManager.handleTableSpace(DBManager.java:544)
        at herddb.core.DBManager.manageTableSpaces(DBManager.java:1189)
        at herddb.core.DBManager.executeActivator(DBManager.java:1135)
        at herddb.core.DBManager.access$500(DBManager.java:120)
        at herddb.core.DBManager$Activator.run(DBManager.java:1078)
        at java.lang.Thread.run(java.base@14/Thread.java:832)

```

**Comment by hamadodene** [comment]
Thanks, @eolivelli  , I will fix it this week.
I think the best solution is to not apply consistency log entry in recovery mode;
What do you think about it?

**Comment by eolivelli** [comment]
@hamadodene yes.
it can be an option.
Please test manually the implementation on a real cluster.

We should also add a couple of test cases with a restart:
- clustermode, issue a TABLESPACECONSISTENCY check, then restart the leader and then restart a follower

**Comment by hamadodene** [comment]
I reproduced the problem with the tests.
I added a new variable in  BookkeeperCommitLog.java for not accept consistency check log entry (Is true  only for  the leader node). 
For the follower i think is ok have consistency check during recovery.

```
private final boolean skipTableConsistencyCheckDuringRecovery = true;
  if (number.after(snapshotSequenceNumber) && !skipTableConsistencyCheckDuringRecovery) {
                                        if (LOGGER.isLoggable(Level.FINEST)) {
```
It can be a good option?
Tomorrow i will test manually my implementation.
