### ISSUE TITLE
NPE when a create table without arguments is run

### ISSUE THREAD

**Issue by hamadodene** [diennea/herddb#604]
`  SEVERE: NettyChannel{name=unnamed, id=5, socket=[id: 0x897ece84, L:/10.162.1.11:8000 - R:/10.162.1.11:56008] pending 0 msgs}: error java.lang.NullPointerException
java.lang.NullPointerException
        at herddb.sql.DDLSQLPlanner.buildCreateTableStatement(DDLSQLPlanner.java:346)
        at herddb.sql.DDLSQLPlanner.plan(DDLSQLPlanner.java:278)
        at herddb.sql.DDLSQLPlanner.translate(DDLSQLPlanner.java:251)
        at herddb.sql.CalcitePlanner.translate(CalcitePlanner.java:248)
        at herddb.server.ServerSideConnectionPeer.handleExecuteStatement(ServerSideConnectionPeer.java:707)
        at herddb.server.ServerSideConnectionPeer.requestReceived(ServerSideConnectionPeer.java:139)
        at herddb.network.netty.NettyChannel.lambda$handlePduRequest$0(NettyChannel.java:97)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:830)
`

**Comment by hamadodene** [comment]
Example:
"create table hama"
I know it's not the correct way, but i think is better to handle the error.
