### ISSUE TITLE
ReadTimeoutException when the connection remains open for too long without load

### ISSUE THREAD

**Issue by hamadodene** [diennea/herddb#606]
```
20-05-29-13-44-37       herddb.network.netty.ClientInboundMessageHandler May 29, 2020 1:44:37 PM herddb.network.netty.ClientInboundMessageHandler exceptionCaught
SEVERE: error on channel ChannelHandlerContext(ClientInboundMessageHandler#0, [id: 0xfb357513, L:/10.200.85.223:45820 - R:hostname/ip:7000])
io.netty.handler.timeout.ReadTimeoutException
```

```
20-05-29-10-28-37       herddb.network.netty.NettyChannel May 29, 2020 10:28:37 AM herddb.network.netty.NettyChannel exceptionCaught
SEVERE: NettyChannel{name=hostname:7000, id=127, socket=[id: 0x46615718, L:/10.200.85.223:43892 ! R:hostname/ip:7000] pending 1 msgs} io-error io.netty.handler.timeout.ReadTimeoutException
```

```
20-05-29-10-28-37       herddb.network.netty.NettyChannel May 29, 2020 10:28:37 AM herddb.network.netty.NettyChannel$1 operationComplete
SEVERE: herddb.network.netty.NettyChannel$1@7916736e: error java.nio.channels.ClosedChannelException
java.nio.channels.ClosedChannelException
        at io.netty.channel.AbstractChannel$AbstractUnsafe.newClosedChannelException(AbstractChannel.java:957)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:865)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
        at io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:304)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:697)
        at io.netty.handler.codec.MessageToMessageEncoder.writePromiseCombiner(MessageToMessageEncoder.java:137)
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:117)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
        at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:830) 
```

**Comment by eolivelli** [comment]
@hamadodene I have added a test case on #607 in order to demonstrate that this error has no functional impact.
You can set a longer client.timeout in order to not see many errors like that, or you can set it to 0 in order to disable it at all

**Comment by hamadodene** [comment]
Thanks @eolivelli, I will test it tomorrow in my cluster
