### ISSUE TITLE
Follower nodes should not try to rollback abandoned transactions

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#610]
**BUG REPORT**

1. Please describe the issue you observed:

Currently Follower nodes try to rollback abandoned transactions, resulting in a potential inconsistency for the system.
The follower tries to write to the WAL.

```
20-06-09-18-45-01       herddb.cluster.BookkeeperCommitLog Jun 09, 2020 6:45:01 PM herddb.cluster.BookkeeperCommitLog log
SEVERE: Cannot get a valid writer for q96 (855ae8455d58408cb3e03d2c09423104)
herddb.log.LogNotAvailableException: herddb.log.LogNotAvailableException: java.lang.Exception: ledgers actual list was fenced, expecting version 1 org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /emailsuccess/ledgers/855ae8455d58408cb3e03d2c09423104
        at herddb.cluster.ZookeeperMetadataStorageManager.saveActualLedgersList(ZookeeperMetadataStorageManager.java:262)
        at herddb.cluster.BookkeeperCommitLog.openNewLedger(BookkeeperCommitLog.java:463)
        at herddb.cluster.BookkeeperCommitLog.getValidWriter(BookkeeperCommitLog.java:356)
        at herddb.cluster.BookkeeperCommitLog.log(BookkeeperCommitLog.java:374)
        at herddb.core.TableSpaceManager.forceTransactionRollback(TableSpaceManager.java:1110)
        at herddb.core.TableSpaceManager.processAbandonedTransactions(TableSpaceManager.java:790)
        at herddb.core.DBManager.executeActivator(DBManager.java:1110)
        at herddb.core.DBManager.access$500(DBManager.java:114)
        at herddb.core.DBManager$Activator.run(DBManager.java:1028)
        at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: herddb.log.LogNotAvailableException: java.lang.Exception: ledgers actual list was fenced, expecting version 1 org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /emailsuccess/ledgers/855ae8455d58408cb3e03d2c09423104
        at herddb.cluster.ZookeeperMetadataStorageManager.saveActualLedgersList(ZookeeperMetadataStorageManager.java:255)
        ... 9 more
Caused by: java.lang.Exception: ledgers actual list was fenced, expecting version 1 org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /emailsuccess/ledgers/855ae8455d58408cb3e03d2c09423104
        ... 10 more
Caused by: org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /emailsuccess/ledgers/855ae8455d58408cb3e03d2c09423104
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:122)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
        at org.apache.zookeeper.ZooKeeper.setData(ZooKeeper.java:2384)
        at herddb.cluster.ZookeeperMetadataStorageManager.saveActualLedgersList(ZookeeperMetadataStorageManager.java:248)
        ... 9 more
```

Suggestion:
- do no force rollback of abandoned transactions on follower. the follower will rollback the transaction when it reads from the log the command written by the leader

**Comment by eolivelli** [comment]
implemented in 0.16.x
