### ISSUE TITLE
After "RuntimeException: timed out acquiring lock for write" the tablespace is stuck

### ISSUE THREAD

**Issue by hamadodene** [diennea/herddb#618]
I found this Exception during database activities:
```
20-06-19-14-26-18       herddb.core.DBManager Jun 19, 2020 2:26:18 PM herddb.core.DBManager executePlanAsync
SEVERE: uncaught error
java.lang.RuntimeException: timed out acquiring lock for write
        at herddb.utils.LocalLockManager.acquireWriteLockForKey(LocalLockManager.java:112)
        at herddb.core.TableManager.lockForWrite(TableManager.java:1025)
        at herddb.core.TableManager.access$2200(TableManager.java:125)
        at herddb.core.TableManager$1RecordProcessor.accept(TableManager.java:3204)
        at herddb.core.TableManager.accessTableData(TableManager.java:3269)
        at herddb.core.TableManager.executeDeleteAsync(TableManager.java:1316)
        at herddb.core.TableManager.executeStatementAsync(TableManager.java:551)
        at herddb.core.TableSpaceManager.executeTableAwareStatement(TableSpaceManager.java:1372)
        at herddb.core.TableSpaceManager.executeStatementAsyncInternal(TableSpaceManager.java:1268)
        at herddb.core.TableSpaceManager.executeStatementAsync(TableSpaceManager.java:1238)
        at herddb.core.DBManager.executeStatementAsync(DBManager.java:662)
        at herddb.core.DBManager.executePlanAsync(DBManager.java:719)
        at herddb.server.ServerSideConnectionPeer.handleExecuteStatement(ServerSideConnectionPeer.java:722)
        at herddb.server.ServerSideConnectionPeer.requestReceived(ServerSideConnectionPeer.java:139)
        at herddb.network.netty.NettyChannel.lambda$handlePduRequest$0(NettyChannel.java:97)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:830)
```
Checking the dump we noticed that the checkpoint was unable to start:

```
hdb-papera-activator" #33 daemon prio=5 os_prio=0 cpu=91247.76ms elapsed=23015.03s tid=0x00007eff11b6d000 nid=0x15d4 waiting on condition  [0x00007efe404bb000]
   java.lang.Thread.State: WAITING (parking)
    at jdk.internal.misc.Unsafe.park(java.base@13.0.2/Native Method)
    - parking to wait for  <0x00000007070cd690> (a java.util.concurrent.locks.StampedLock)
    at java.util.concurrent.locks.LockSupport.park(java.base@13.0.2/LockSupport.java:194)
    at java.util.concurrent.locks.StampedLock.acquireWrite(java.base@13.0.2/StampedLock.java:1329)
    at java.util.concurrent.locks.StampedLock.writeLock(java.base@13.0.2/StampedLock.java:475)
    at herddb.core.TableSpaceManager.acquireWriteLock(TableSpaceManager.java:1399)
    at herddb.core.TableSpaceManager.checkpoint(TableSpaceManager.java:1837)
    at herddb.core.DBManager.checkpoint(DBManager.java:838)
    at herddb.core.DBManager.executeActivator(DBManager.java:1146)
    at herddb.core.DBManager.access$500(DBManager.java:120)
    at herddb.core.DBManager$Activator.run(DBManager.java:1078)
    at java.lang.Thread.run(java.base@13.0.2/Thread.java:830)
```
and the other threads are waiting for the readlock on the checkpoint:
```
hdb-papera-activator" #33 daemon prio=5 os_prio=0 cpu=91247.76ms elapsed=23015.03s tid=0x00007eff11b6d000 nid=0x15d4 waiting on condition  [0x00007efe404bb000]
   java.lang.Thread.State: WAITING (parking)
    at jdk.internal.misc.Unsafe.park(java.base@13.0.2/Native Method)
    - parking to wait for  <0x00000007070cd690> (a java.util.concurrent.locks.StampedLock)
    at java.util.concurrent.locks.LockSupport.park(java.base@13.0.2/LockSupport.java:194)
    at java.util.concurrent.locks.StampedLock.acquireWrite(java.base@13.0.2/StampedLock.java:1329)
    at java.util.concurrent.locks.StampedLock.writeLock(java.base@13.0.2/StampedLock.java:475)
    at herddb.core.TableSpaceManager.acquireWriteLock(TableSpaceManager.java:1399)
    at herddb.core.TableSpaceManager.checkpoint(TableSpaceManager.java:1837)
    at herddb.core.DBManager.checkpoint(DBManager.java:838)
    at herddb.core.DBManager.executeActivator(DBManager.java:1146)
    at herddb.core.DBManager.access$500(DBManager.java:120)
    at herddb.core.DBManager$Activator.run(DBManager.java:1078)
    at java.lang.Thread.run(java.base@13.0.2/Thread.java:830)

```

**Comment by eolivelli** [comment]
I am trying to reproduce this problem in a test case.

**Comment by hamadodene** [comment]
Good, thx @eolivelli
