### ISSUE TITLE
Implement JDBC ResultSet#getBytes

### ISSUE THREAD

**Issue by eolivelli** [diennea/herddb#627]
**FEATURE REQUEST**

We need to implement support for getBytes()
```

java.lang.UnsupportedOperationException: Not supported yet.
	at herddb.jdbc.HerdDBResultSet.getBytes(HerdDBResultSet.java:338)
	at org.apache.commons.dbcp.DelegatingResultSet.getBytes(DelegatingResultSet.java:241)
	at org.apache.commons.dbcp.DelegatingResultSet.getBytes(DelegatingResultSet.java:241)

```

**Comment by eolivelli** [comment]
fixed in 0.17
