### ISSUE TITLE
test failure on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [diennea/herddb#744]
Including the tests results in this, for example: 

[jw@cn06 herddb]$ mvn install
...
INFO: SessionTrackerImpl exited loop!
Apr 16, 2021 10:13:02 AM org.apache.bookkeeper.proto.PerChannelBookieClient checkTimeoutOnPendingOperations
INFO: Timed-out 1 operations to channel [id: 0xa7279170, L:local:E:a0b16da4 - R:local:cn06:34123] for cn06:34123
Apr 16, 2021 10:13:02 AM org.apache.bookkeeper.client.PendingAddOp writeComplete
WARNING: Failed to write entry (0, 5): Bookie operation timeout
Apr 16, 2021 10:13:02 AM org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl selectRandomInternal
WARNING: Failed to find 1 bookies : excludeBookies [<Bookie:cn06:34123>], allBookies [<Bookie:cn06:34123>].
Apr 16, 2021 10:13:02 AM org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl selectFromNetworkLocation
WARNING: Failed to choose a bookie: excluded [<Bookie:cn06:34123>], fallback to choose bookie randomly from the cluster.
Apr 16, 2021 10:13:02 AM org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl selectRandomInternal
WARNING: Failed to find 1 bookies : excludeBookies [<Bookie:cn06:34123>], allBookies [<Bookie:cn06:34123>].
Apr 16, 2021 10:13:02 AM org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl selectRandomInternal
WARNING: Failed to find 1 bookies : excludeBookies [<Bookie:cn06:34123>], allBookies [<Bookie:cn06:34123>].
Apr 16, 2021 10:13:02 AM org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl selectFromNetworkLocation
WARNING: Failed to choose a bookie: excluded [<Bookie:cn06:34123>], fallback to choose bookie randomly from the cluster.
Apr 16, 2021 10:13:02 AM org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl selectRandomInternal
WARNING: Failed to find 1 bookies : excludeBookies [<Bookie:cn06:34123>], allBookies [<Bookie:cn06:34123>].
Apr 16, 2021 10:13:02 AM org.apache.bookkeeper.client.MetadataUpdateLoop writeLoop
SEVERE: UpdateLoop(ledgerId=0,loopId=37cbcc34) Exception updating
org.apache.bookkeeper.client.BKException$BKNotEnoughBookiesException: Not enough non-faulty bookies available
        at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl.selectRandomInternal(RackawareEnsemblePlacementPolicyImpl.java:781)
        at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl.selectRandom(RackawareEnsemblePlacementPolicyImpl.java:699)
        at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl.selectFromNetworkLocation(RackawareEnsemblePlacementPolicyImpl.java:588)
        at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicy.selectFromNetworkLocation(RackawareEnsemblePlacementPolicy.java:206)
        at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl.selectFromNetworkLocation(RackawareEnsemblePlacementPolicyImpl.java:548)
        at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicy.selectFromNetworkLocation(RackawareEnsemblePlacementPolicy.java:227)
        at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl.replaceBookie(RackawareEnsemblePlacementPolicyImpl.java:476)
        at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicy.replaceBookie(RackawareEnsemblePlacementPolicy.java:120)
        at org.apache.bookkeeper.client.BookieWatcherImpl.replaceBookie(BookieWatcherImpl.java:334)
        at org.apache.bookkeeper.client.EnsembleUtils.replaceBookiesInEnsemble(EnsembleUtils.java:71)
        at org.apache.bookkeeper.client.LedgerHandle.lambda$ensembleChangeLoop$2(LedgerHandle.java:1935)
        at org.apache.bookkeeper.client.MetadataUpdateLoop.writeLoop(MetadataUpdateLoop.java:134)
        at org.apache.bookkeeper.client.MetadataUpdateLoop.run(MetadataUpdateLoop.java:123)
        at org.apache.bookkeeper.client.LedgerHandle.ensembleChangeLoop(LedgerHandle.java:1954)
        at org.apache.bookkeeper.client.LedgerHandle.handleBookieFailure(LedgerHandle.java:1903)
        at org.apache.bookkeeper.client.PendingAddOp.writeComplete(PendingAddOp.java:378)
        at org.apache.bookkeeper.proto.PerChannelBookieClient$AddCompletion.writeComplete(PerChannelBookieClient.java:2160)
        at org.apache.bookkeeper.proto.PerChannelBookieClient$AddCompletion.lambda$errorOut$0(PerChannelBookieClient.java:2183)
        at org.apache.bookkeeper.proto.PerChannelBookieClient$CompletionValue$1.safeRun(PerChannelBookieClient.java:1672)
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

Apr 16, 2021 10:13:02 AM org.apache.bookkeeper.client.LedgerHandle lambda$ensembleChangeLoop$3
WARNING: [EnsembleChange(ledger:0, change-id:0000000001)][attempt:1] Exception changing ensemble
org.apache.bookkeeper.client.BKException$BKNotEnoughBookiesException: Not enough non-faulty bookies available
        at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl.selectRandomInternal(RackawareEnsemblePlacementPolicyImpl.java:781)
        at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl.selectRandom(RackawareEnsemblePlacementPolicyImpl.java:699)
        at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl.selectFromNetworkLocation(RackawareEnsemblePlacementPolicyImpl.java:588)
        at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicy.selectFromNetworkLocation(RackawareEnsemblePlacementPolicy.java:206)
        at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl.selectFromNetworkLocation(RackawareEnsemblePlacementPolicyImpl.java:548)
        at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicy.selectFromNetworkLocation(RackawareEnsemblePlacementPolicy.java:227)
        at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl.replaceBookie(RackawareEnsemblePlacementPolicyImpl.java:476)
        at org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicy.replaceBookie(RackawareEnsemblePlacementPolicy.java:120)
        at org.apache.bookkeeper.client.BookieWatcherImpl.replaceBookie(BookieWatcherImpl.java:334)
        at org.apache.bookkeeper.client.EnsembleUtils.replaceBookiesInEnsemble(EnsembleUtils.java:71)
        at org.apache.bookkeeper.client.LedgerHandle.lambda$ensembleChangeLoop$2(LedgerHandle.java:1935)
        at org.apache.bookkeeper.client.MetadataUpdateLoop.writeLoop(MetadataUpdateLoop.java:134)
        at org.apache.bookkeeper.client.MetadataUpdateLoop.run(MetadataUpdateLoop.java:123)
        at org.apache.bookkeeper.client.LedgerHandle.ensembleChangeLoop(LedgerHandle.java:1954)
        at org.apache.bookkeeper.client.LedgerHandle.handleBookieFailure(LedgerHandle.java:1903)
        at org.apache.bookkeeper.client.PendingAddOp.writeComplete(PendingAddOp.java:378)
        at org.apache.bookkeeper.proto.PerChannelBookieClient$AddCompletion.writeComplete(PerChannelBookieClient.java:2160)
        at org.apache.bookkeeper.proto.PerChannelBookieClient$AddCompletion.lambda$errorOut$0(PerChannelBookieClient.java:2183)
        at org.apache.bookkeeper.proto.PerChannelBookieClient$CompletionValue$1.safeRun(PerChannelBookieClient.java:1672)
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

Apr 16, 2021 10:13:02 AM org.apache.bookkeeper.client.LedgerHandle handleUnrecoverableErrorDuringAdd
SEVERE: Closing ledger 0 due to NotEnoughBookiesException: Not enough non-faulty bookies available
Apr 16, 2021 10:13:02 AM org.apache.bookkeeper.client.PendingAddOp submitCallback
SEVERE: Write of ledger entry to quorum failed: L0 E5
Apr 16, 2021 10:13:02 AM herddb.cluster.BookkeeperCommitLog handleBookKeeperFailure
SEVERE: bookkeeper async failure on tablespace herd (abd8af59738f40f4b16fcca2e5f605ce) while writing entry LE{t=2,tx=0,tn=t1,k=00000004,v=,ts=1618560776314}
org.apache.bookkeeper.client.BKException$BKNotEnoughBookiesException: Not enough non-faulty bookies available
        at org.apache.bookkeeper.client.SyncCallbackUtils.finish(SyncCallbackUtils.java:83)
        at org.apache.bookkeeper.client.SyncCallbackUtils$SyncAddCallback.addComplete(SyncCallbackUtils.java:251)
        at org.apache.bookkeeper.client.AsyncCallback$AddCallback.addCompleteWithLatency(AsyncCallback.java:92)
        at org.apache.bookkeeper.client.PendingAddOp.submitCallback(PendingAddOp.java:431)
        at org.apache.bookkeeper.client.LedgerHandle.errorOutPendingAdds(LedgerHandle.java:1799)
        at org.apache.bookkeeper.client.LedgerHandle$5.safeRun(LedgerHandle.java:574)
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

Apr 16, 2021 10:13:02 AM herddb.cluster.BookkeeperCommitLog handleBookKeeperFailure
SEVERE: bookkeeper failure for tablespace herd (abd8af59738f40f4b16fcca2e5f605ce)
org.apache.bookkeeper.client.BKException$BKNotEnoughBookiesException: Not enough non-faulty bookies available
        at org.apache.bookkeeper.client.SyncCallbackUtils.finish(SyncCallbackUtils.java:83)
        at org.apache.bookkeeper.client.SyncCallbackUtils$SyncAddCallback.addComplete(SyncCallbackUtils.java:251)
        at org.apache.bookkeeper.client.AsyncCallback$AddCallback.addCompleteWithLatency(AsyncCallback.java:92)
        at org.apache.bookkeeper.client.PendingAddOp.submitCallback(PendingAddOp.java:431)
        at org.apache.bookkeeper.client.LedgerHandle.errorOutPendingAdds(LedgerHandle.java:1799)
        at org.apache.bookkeeper.client.LedgerHandle$5.safeRun(LedgerHandle.java:574)
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

status leader:true failed:true
tableSpaceManager_after_failure:TableSpaceManager [nodeId=server1, tableSpaceName=herd, tableSpaceUUID=abd8af59738f40f4b16fcca2e5f605ce]
tableSpaceManager:TableSpaceManager [nodeId=server1, tableSpaceName=herd, tableSpaceUUID=abd8af59738f40f4b16fcca2e5f605ce]
Apr 16, 2021 10:13:02 AM herddb.core.DBManager$Activator run
INFO: server1 activator resumed
...

**Comment by eolivelli** [comment]
Is this test consistently failing ?

`"WARNING: Failed to write entry (0, 5): Bookie operation timeout" `means that the bookie did not answer in time.
are you running on a small machine or overwhelmed machine ?

**Comment by eolivelli** [comment]
@LutzWeischerFujitsu feel free to join us on slack in official Apache BookKeeper workspace on channel #herddb 

https://bookkeeper.apache.org/community/slack/

**Comment by LutzWeischerFujitsu** [comment]
I tried again and let it run. It ends with 

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Herd DB 0.23.0-SNAPSHOT:
[INFO]
[INFO] Herd DB ............................................ SUCCESS [  0.417 s]
[INFO] HerdDB Utils ....................................... SUCCESS [ 47.410 s]
[INFO] HerdDB Mock Dependencies ........................... SUCCESS [  0.127 s]
[INFO] HerdDB Networking .................................. SUCCESS [ 14.947 s]
[INFO] HerdDB Core ........................................ SUCCESS [  01:03 h]
[INFO] HerdDB JDBC Driver ................................. SUCCESS [07:17 min]
[INFO] HerdDB Collections Framework. ...................... SUCCESS [ 27.209 s]
[INFO] HerdDB UI .......................................... SUCCESS [  4.287 s]
[INFO] HerdDB CLI ......................................... SUCCESS [ 22.278 s]
[INFO] HerdDB Services .................................... SUCCESS [01:12 min]
[INFO] HerdDB Benchmarks .................................. SUCCESS [20:54 min]
[INFO] HerdDB Website ..................................... SUCCESS [  0.099 s]
[INFO] HerdDB Site skin ................................... SUCCESS [  0.240 s]
[INFO] HerdDB Backward compatibility tests ................ SUCCESS [ 17.044 s]
[INFO] HerdDB Third Party compatibility ................... SUCCESS [  0.025 s]
[INFO] HerdDB OpenJPA Provider ............................ SUCCESS [  0.109 s]
[INFO] HerdDB Third Party compatibility tests - OpenJPA ... SUCCESS [ 17.339 s]
[INFO] HerdDB Docker ...................................... SUCCESS [  1.451 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:35 h
[INFO] Finished at: 2021-04-19T12:17:00+02:00
[INFO] ------------------------------------------------------------------------
(base) [jw@cn06 herddb]$ 

In between I find messages like 

SEVERE: Booting Apache Bookkeeper on port 3181,  base directory: /data/jw/herddb/herddb-bench/target/junit4789376793772061204/junit6290461890285277317/bookie
Apr 19, 2021 12:06:04 PM herddb.cluster.EmbeddedBookie dumpBookieConfiguration
SEVERE: Dumped actual Bookie configuration to /data/jw/herddb/herddb-bench/target/junit4789376793772061204/junit6290461890285277317/bookie/embedded.bookie.properties

Apr 19, 2021 12:09:06 PM herddb.server.LocalNodeIdManager readLocalNodeId
SEVERE: Cannot find file /data/jw/herddb/herddb-bench/target/junit17855065053714899574/junit6144003591622211148/data/nodeid

**Comment by eolivelli** [comment]
We should turn those log line from SEVERE to INFO.

Do you mind sending a little patch in order to fix that annoying log level ?

**Comment by eolivelli** [comment]
btw I am happy that it was only a flaky test in your env

**Comment by LutzWeischerFujitsu** [comment]
Enrico, thanks for asking, but I'm not a developer. 
So, I consider this software to work, too.

**Comment by eolivelli** [comment]
No problem @LutzWeischerFujitsu 
thanks for your feedback, feel free to close this issue if you are able to pass the build.

If you only have to build it locally then you can use "mvn clean install -DskipTests"

if you have to build the docker image checkout the "docker" folder or look for it on dockerhub
